using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;

namespace CyrFlip
{
    /// <summary>
    /// One vendored vocabulary glyph (ICON-SET): SVG path data on the contract's 24 x 24 grid. The table
    /// of them is <c>Glyphs.g.cs</c>, generated by <c>tools/IconGen</c> and never edited by hand.
    /// <see cref="Transform"/> is the SVG matrix (a b c d e f) of the <c>&lt;g&gt;</c> the exporter wrapped two
    /// of the files in, or null.
    /// </summary>
    internal sealed class GlyphRecord
    {
        public string Id { get; }
        public string PathData { get; }
        public float[]? Transform { get; }
        public string Status { get; }
        /// <summary><c>fixed</c> or <c>mirror</c>: mirrored in a right-to-left layout only when the record says so.</summary>
        public string Rtl { get; }
        public string Source { get; }
        /// <summary>The SVG <c>fill-rule</c> was <c>evenodd</c>; false is the nonzero default.</summary>
        public bool EvenOdd { get; }

        public GlyphRecord(string id, string pathData, float[]? transform, string status, string rtl, string source, bool evenOdd = false)
        {
            Id = id; PathData = pathData; Transform = transform; Status = status; Rtl = rtl; Source = source; EvenOdd = evenOdd;
        }
    }

    /// <summary>
    /// SVG path data to a <see cref="GraphicsPath"/> (ticket S0022 A1). net48 has no SVG renderer and the
    /// app takes no NuGet dependency, so this reads the commands the vocabulary uses - and the rest of the
    /// grammar, since a catalog MINOR may bring any of it: M L H V C S Q T A Z, absolute and relative.
    /// The fill mode is <b>Winding</b>, SVG's nonzero default: GDI+'s own Alternate punches holes into
    /// glyphs whose sub-paths overlap. A glyph whose SVG says <c>fill-rule="evenodd"</c> is the one case
    /// that asks for Alternate (<paramref name="evenOdd"/>) - the key caps of "app.shortcuts" are hollow
    /// because of it.
    /// A path that does not parse yields null, never an exception (the control keeps its text caption).
    /// </summary>
    internal static class GlyphPath
    {
        public static GraphicsPath? Parse(string data, float[]? transform = null, bool evenOdd = false)
        {
            if (string.IsNullOrWhiteSpace(data)) return null;
            try
            {
                GraphicsPath? path = ParseCore(data);
                if (path == null) return null;
                path.FillMode = evenOdd ? FillMode.Alternate : FillMode.Winding;
                if (transform != null && transform.Length == 6)
                    using (var matrix = new Matrix(transform[0], transform[1], transform[2], transform[3], transform[4], transform[5]))
                        path.Transform(matrix);
                return path;
            }
            catch (Exception) { return null; }
        }

        private static GraphicsPath? ParseCore(string data)
        {
            var path = new GraphicsPath(FillMode.Winding);
            int i = 0;
            char command = '\0';
            float x = 0, y = 0, startX = 0, startY = 0;
            float lastCtrlX = 0, lastCtrlY = 0;
            char previous = '\0';
            bool figureOpen = false;
            var numbers = new float[7];

            while (true)
            {
                SkipSeparators(data, ref i);
                if (i >= data.Length) break;
                char c = data[i];
                if (char.IsLetter(c)) { command = c; i++; }
                else if (command == '\0') { path.Dispose(); return null; }       // numbers before any command
                else if (command == 'Z' || command == 'z') { path.Dispose(); return null; } // numbers after a close
                else if (command == 'M') command = 'L';                         // implicit lineto after a moveto
                else if (command == 'm') command = 'l';

                bool relative = char.IsLower(command);
                char upper = char.ToUpperInvariant(command);
                int count = ArgumentCount(upper);
                if (count < 0) { path.Dispose(); return null; }

                if (upper == 'Z')
                {
                    if (figureOpen) path.CloseFigure();
                    figureOpen = false;
                    x = startX; y = startY; previous = 'Z';
                    continue;
                }

                for (int n = 0; n < count; n++)
                    if (!ReadNumber(data, ref i, upper == 'A' && (n == 3 || n == 4), out numbers[n])) { path.Dispose(); return null; }

                float ox = relative ? x : 0, oy = relative ? y : 0;
                switch (upper)
                {
                    case 'M':
                        if (figureOpen) path.StartFigure();
                        x = numbers[0] + ox; y = numbers[1] + oy; startX = x; startY = y;
                        figureOpen = false; previous = 'M';
                        continue;
                    case 'L':
                        Line(path, x, y, numbers[0] + ox, numbers[1] + oy, ref figureOpen);
                        x = numbers[0] + ox; y = numbers[1] + oy;
                        break;
                    case 'H':
                        Line(path, x, y, numbers[0] + ox, y, ref figureOpen);
                        x = numbers[0] + ox;
                        break;
                    case 'V':
                        Line(path, x, y, x, numbers[0] + oy, ref figureOpen);
                        y = numbers[0] + oy;
                        break;
                    case 'C':
                    {
                        float c1x = numbers[0] + ox, c1y = numbers[1] + oy, c2x = numbers[2] + ox, c2y = numbers[3] + oy, ex = numbers[4] + ox, ey = numbers[5] + oy;
                        Cubic(path, x, y, c1x, c1y, c2x, c2y, ex, ey, ref figureOpen);
                        lastCtrlX = c2x; lastCtrlY = c2y; x = ex; y = ey;
                        break;
                    }
                    case 'S':
                    {
                        // The first control point is the reflection of the previous cubic's second one.
                        float c1x = previous == 'C' || previous == 'S' ? 2 * x - lastCtrlX : x, c1y = previous == 'C' || previous == 'S' ? 2 * y - lastCtrlY : y;
                        float c2x = numbers[0] + ox, c2y = numbers[1] + oy, ex = numbers[2] + ox, ey = numbers[3] + oy;
                        Cubic(path, x, y, c1x, c1y, c2x, c2y, ex, ey, ref figureOpen);
                        lastCtrlX = c2x; lastCtrlY = c2y; x = ex; y = ey;
                        break;
                    }
                    case 'Q':
                    {
                        float qx = numbers[0] + ox, qy = numbers[1] + oy, ex = numbers[2] + ox, ey = numbers[3] + oy;
                        Quadratic(path, x, y, qx, qy, ex, ey, ref figureOpen);
                        lastCtrlX = qx; lastCtrlY = qy; x = ex; y = ey;
                        break;
                    }
                    case 'T':
                    {
                        float qx = previous == 'Q' || previous == 'T' ? 2 * x - lastCtrlX : x, qy = previous == 'Q' || previous == 'T' ? 2 * y - lastCtrlY : y;
                        float ex = numbers[0] + ox, ey = numbers[1] + oy;
                        Quadratic(path, x, y, qx, qy, ex, ey, ref figureOpen);
                        lastCtrlX = qx; lastCtrlY = qy; x = ex; y = ey;
                        break;
                    }
                    case 'A':
                    {
                        float ex = numbers[5] + ox, ey = numbers[6] + oy;
                        Arc(path, x, y, numbers[0], numbers[1], numbers[2], numbers[3] != 0, numbers[4] != 0, ex, ey, ref figureOpen);
                        x = ex; y = ey;
                        break;
                    }
                }
                previous = upper;
            }
            if (path.PointCount == 0) { path.Dispose(); return null; }
            return path;
        }

        private static int ArgumentCount(char upper)
        {
            switch (upper)
            {
                case 'M': case 'L': case 'T': return 2;
                case 'H': case 'V': return 1;
                case 'C': return 6;
                case 'S': case 'Q': return 4;
                case 'A': return 7;
                case 'Z': return 0;
                default: return -1;
            }
        }

        private static void SkipSeparators(string s, ref int i)
        {
            while (i < s.Length && (char.IsWhiteSpace(s[i]) || s[i] == ',')) i++;
        }

        /// <summary>
        /// One number in SVG's compact grammar: "1.5.5" is 1.5 and .5, "-1-2" is -1 and -2. The two arc flags
        /// are a single digit and may run straight into the next number ("a1 1 0 00.5.5").
        /// </summary>
        private static bool ReadNumber(string s, ref int i, bool flag, out float value)
        {
            value = 0;
            SkipSeparators(s, ref i);
            if (i >= s.Length) return false;
            if (flag)
            {
                if (s[i] != '0' && s[i] != '1') return false;
                value = s[i] - '0'; i++;
                return true;
            }
            int start = i;
            if (s[i] == '+' || s[i] == '-') i++;
            bool digits = false, dot = false;
            while (i < s.Length)
            {
                char c = s[i];
                if (c >= '0' && c <= '9') { digits = true; i++; }
                else if (c == '.' && !dot) { dot = true; i++; }
                else break;
            }
            if (!digits) return false;
            if (i < s.Length && (s[i] == 'e' || s[i] == 'E'))
            {
                int save = i; i++;
                if (i < s.Length && (s[i] == '+' || s[i] == '-')) i++;
                int expStart = i;
                while (i < s.Length && s[i] >= '0' && s[i] <= '9') i++;
                if (i == expStart) i = save;
            }
            if (!float.TryParse(s.Substring(start, i - start), NumberStyles.Float, CultureInfo.InvariantCulture, out value)) return false;
            return !float.IsNaN(value) && !float.IsInfinity(value);
        }

        private static void Line(GraphicsPath path, float x0, float y0, float x1, float y1, ref bool open)
        {
            path.AddLine(x0, y0, x1, y1); open = true;
        }

        private static void Cubic(GraphicsPath path, float x0, float y0, float c1x, float c1y, float c2x, float c2y, float x1, float y1, ref bool open)
        {
            path.AddBezier(x0, y0, c1x, c1y, c2x, c2y, x1, y1); open = true;
        }

        private static void Quadratic(GraphicsPath path, float x0, float y0, float qx, float qy, float x1, float y1, ref bool open)
        {
            // An exact degree elevation: the cubic with the two thirds-way control points.
            Cubic(path, x0, y0, x0 + 2f / 3f * (qx - x0), y0 + 2f / 3f * (qy - y0), x1 + 2f / 3f * (qx - x1), y1 + 2f / 3f * (qy - y1), x1, y1, ref open);
        }

        /// <summary>SVG's endpoint arc (implementation note F.6) as at most a quarter-turn of cubics each.</summary>
        private static void Arc(GraphicsPath path, float x0, float y0, float rxIn, float ryIn, float rotationDeg, bool largeArc, bool sweep, float x1, float y1, ref bool open)
        {
            if (x0 == x1 && y0 == y1) return;
            double rx = Math.Abs(rxIn), ry = Math.Abs(ryIn);
            if (rx == 0 || ry == 0) { Line(path, x0, y0, x1, y1, ref open); return; }
            double phi = rotationDeg * Math.PI / 180, cosPhi = Math.Cos(phi), sinPhi = Math.Sin(phi);
            double dx = (x0 - x1) / 2.0, dy = (y0 - y1) / 2.0;
            double x1p = cosPhi * dx + sinPhi * dy, y1p = -sinPhi * dx + cosPhi * dy;
            double lambda = x1p * x1p / (rx * rx) + y1p * y1p / (ry * ry);
            if (lambda > 1) { double s = Math.Sqrt(lambda); rx *= s; ry *= s; }
            double numerator = rx * rx * ry * ry - rx * rx * y1p * y1p - ry * ry * x1p * x1p;
            double denominator = rx * rx * y1p * y1p + ry * ry * x1p * x1p;
            double factor = denominator == 0 ? 0 : Math.Sqrt(Math.Max(0, numerator / denominator));
            if (largeArc == sweep) factor = -factor;
            double cxp = factor * rx * y1p / ry, cyp = -factor * ry * x1p / rx;
            double cx = cosPhi * cxp - sinPhi * cyp + (x0 + x1) / 2.0, cy = sinPhi * cxp + cosPhi * cyp + (y0 + y1) / 2.0;
            double theta1 = Math.Atan2((y1p - cyp) / ry, (x1p - cxp) / rx);
            double theta2 = Math.Atan2((-y1p - cyp) / ry, (-x1p - cxp) / rx);
            double delta = theta2 - theta1;
            if (sweep && delta < 0) delta += 2 * Math.PI;
            else if (!sweep && delta > 0) delta -= 2 * Math.PI;

            int segments = Math.Max(1, (int)Math.Ceiling(Math.Abs(delta) / (Math.PI / 2) - 1e-9));
            double step = delta / segments;
            double t = 4.0 / 3.0 * Math.Tan(step / 4);
            double angle = theta1;
            double px = x0, py = y0;
            for (int s = 0; s < segments; s++)
            {
                double cosA = Math.Cos(angle), sinA = Math.Sin(angle), cosB = Math.Cos(angle + step), sinB = Math.Sin(angle + step);
                double e1x = cosA - t * sinA, e1y = sinA + t * cosA;
                double e2x = cosB + t * sinB, e2y = sinB - t * cosB;
                double c1x = cx + rx * cosPhi * e1x - ry * sinPhi * e1y, c1y = cy + rx * sinPhi * e1x + ry * cosPhi * e1y;
                double c2x = cx + rx * cosPhi * e2x - ry * sinPhi * e2y, c2y = cy + rx * sinPhi * e2x + ry * cosPhi * e2y;
                double ex = s == segments - 1 ? x1 : cx + rx * cosPhi * cosB - ry * sinPhi * sinB;
                double ey = s == segments - 1 ? y1 : cy + rx * sinPhi * cosB + ry * cosPhi * sinB;
                Cubic(path, (float)px, (float)py, (float)c1x, (float)c1y, (float)c2x, (float)c2y, (float)ex, (float)ey, ref open);
                px = ex; py = ey; angle += step;
            }
        }
    }
}
