namespace CyrFlip
{
    /// <summary>
    /// The Graphics tab (ticket S0026): the screen region capture - its settings, its tray item, the chord dialog title
    /// and the balloons of the screen region capture.
    /// </summary>
    internal static partial class Localization
    {
        private static void AddGraphicsStrings()
        {
            Add("Графика",
                en: "Graphics",
                uk: "Графіка",
                de: "Grafik",
                it: "Grafica",
                es: "Gráficos",
                fr: "Graphisme",
                pt: "Gráficos",
                ar: "الرسوميات",
                hi: "ग्राफ़िक्स",
                bn: "গ্রাফিক্স",
                ur: "گرافکس",
                zh: "图形");

            Add("Инструменты, которые работают с тем, что сейчас на экране. Всё остаётся на этом компьютере.",
                en: "Tools that work with what is on the screen right now. Everything stays on this computer.",
                uk: "Інструменти, які працюють із тим, що зараз на екрані. Усе залишається на цьому комп'ютері.",
                de: "Werkzeuge für das, was gerade auf dem Bildschirm zu sehen ist. Alles bleibt auf diesem Computer.",
                it: "Strumenti che lavorano con ciò che è ora sullo schermo. Tutto resta su questo computer.",
                es: "Herramientas que trabajan con lo que hay ahora en la pantalla. Todo se queda en este equipo.",
                fr: "Des outils qui travaillent avec ce qui est à l'écran en ce moment. Tout reste sur cet ordinateur.",
                pt: "Ferramentas que trabalham com o que está agora no ecrã. Tudo fica neste computador.",
                ar: "أدوات تعمل على ما يظهر على الشاشة الآن. يبقى كل شيء على هذا الكمبيوتر.",
                hi: "ऐसे टूल जो अभी स्क्रीन पर दिख रही चीज़ों के साथ काम करते हैं। सब कुछ इसी कंप्यूटर पर रहता है।",
                bn: "এমন টুল যা এখন স্ক্রিনে যা আছে তা নিয়ে কাজ করে। সবকিছু এই কম্পিউটারেই থাকে।",
                ur: "ایسے ٹولز جو اس وقت اسکرین پر موجود چیزوں کے ساتھ کام کرتے ہیں۔ سب کچھ اسی کمپیوٹر پر رہتا ہے۔",
                zh: "处理当前屏幕内容的工具。所有内容都留在这台电脑上。");

            Add("Снимок области экрана",
                en: "Screen region capture",
                uk: "Знімок області екрана",
                de: "Bildschirmausschnitt aufnehmen",
                it: "Cattura di un'area dello schermo",
                es: "Captura de una zona de la pantalla",
                fr: "Capture d'une zone de l'écran",
                pt: "Captura de uma área do ecrã",
                ar: "لقطة لجزء من الشاشة",
                hi: "स्क्रीन के हिस्से का स्क्रीनशॉट",
                bn: "স্ক্রিনের একটি অংশের স্ক্রিনশট",
                ur: "اسکرین کے حصے کا اسکرین شاٹ",
                zh: "屏幕区域截图");

            Add("снимок области экрана",
                en: "screen region capture",
                uk: "знімок області екрана",
                de: "Bildschirmausschnitt",
                it: "cattura di un'area dello schermo",
                es: "captura de una zona de la pantalla",
                fr: "capture d'une zone de l'écran",
                pt: "captura de uma área do ecrã",
                ar: "لقطة لجزء من الشاشة",
                hi: "स्क्रीन के हिस्से का स्क्रीनशॉट",
                bn: "স্ক্রিনের অংশের স্ক্রিনশট",
                ur: "اسکرین کے حصے کا اسکرین شاٹ",
                zh: "屏幕区域截图");

            Add("Экран замирает, вы выделяете прямоугольник мышью, и картинка сразу в буфере обмена. Esc или правая кнопка - отмена. Одну комбинацию нельзя отдать двум действиям CyrFlip.",
                en: "The screen freezes, you drag a rectangle with the mouse, and the picture is on the clipboard at once. Esc or the right button cancels. One chord cannot belong to two CyrFlip actions.",
                uk: "Екран завмирає, ви виділяєте прямокутник мишею, і зображення одразу в буфері обміну. Esc або права кнопка - скасування. Одну комбінацію не можна віддати двом діям CyrFlip.",
                de: "Der Bildschirm friert ein, Sie ziehen mit der Maus ein Rechteck auf, und das Bild liegt sofort in der Zwischenablage. Esc oder die rechte Maustaste bricht ab. Eine Kombination kann nicht zwei CyrFlip-Aktionen gehören.",
                it: "Lo schermo si blocca, trascini un rettangolo con il mouse e l'immagine è subito negli appunti. Esc o il tasto destro annullano. Una combinazione non può appartenere a due azioni di CyrFlip.",
                es: "La pantalla se congela, arrastra un rectángulo con el ratón y la imagen queda al instante en el portapapeles. Esc o el botón derecho cancelan. Una combinación no puede pertenecer a dos acciones de CyrFlip.",
                fr: "L'écran se fige, vous tracez un rectangle à la souris et l'image est aussitôt dans le presse-papiers. Échap ou le bouton droit annule. Une combinaison ne peut pas appartenir à deux actions de CyrFlip.",
                pt: "O ecrã congela, arrasta um retângulo com o rato e a imagem fica de imediato na área de transferência. Esc ou o botão direito cancelam. Uma combinação não pode pertencer a duas ações do CyrFlip.",
                ar: "تتجمد الشاشة، وتحدد مستطيلًا بالفأرة، فتصبح الصورة في الحافظة فورًا. ‏Esc أو الزر الأيمن للإلغاء. لا يمكن إسناد اختصار واحد إلى إجراءين في CyrFlip.",
                hi: "स्क्रीन रुक जाती है, आप माउस से एक आयत खींचते हैं, और चित्र तुरंत क्लिपबोर्ड पर होता है। Esc या दायाँ बटन रद्द करता है। एक संयोजन CyrFlip की दो क्रियाओं को नहीं दिया जा सकता।",
                bn: "স্ক্রিন স্থির হয়ে যায়, আপনি মাউস দিয়ে একটি আয়তক্ষেত্র টানেন, আর ছবিটি সঙ্গে সঙ্গে ক্লিপবোর্ডে চলে যায়। Esc বা ডান বোতাম বাতিল করে। একটি সমন্বয় CyrFlip-এর দুটি কাজে দেওয়া যায় না।",
                ur: "اسکرین رک جاتی ہے، آپ ماؤس سے ایک مستطیل کھینچتے ہیں، اور تصویر فوراً کلپ بورڈ پر ہوتی ہے۔ Esc یا دایاں بٹن منسوخ کرتا ہے۔ ایک مجموعہ CyrFlip کے دو کاموں کو نہیں دیا جا سکتا۔",
                zh: "屏幕会定格，您用鼠标拖出一个矩形，图片立即进入剪贴板。按 Esc 或鼠标右键取消。同一组合键不能分配给 CyrFlip 的两个操作。");

            Add("Сделать снимок области",
                en: "Capture a region",
                uk: "Зробити знімок області",
                de: "Ausschnitt aufnehmen",
                it: "Cattura un'area",
                es: "Capturar una zona",
                fr: "Capturer une zone",
                pt: "Capturar uma área",
                ar: "التقاط جزء من الشاشة",
                hi: "हिस्से का स्क्रीनशॉट लें",
                bn: "একটি অংশের স্ক্রিনশট নিন",
                ur: "حصے کا اسکرین شاٹ لیں",
                zh: "截取区域");

            Add("То же, что пункт в меню трея. Всплывающую подсказку или открытое меню поймает только комбинация: щелчок по трею их закрывает.",
                en: "The same as the tray menu item. Only the chord catches a tooltip or an open menu: a click on the tray closes them.",
                uk: "Те саме, що пункт у меню трею. Спливну підказку чи відкрите меню впіймає лише комбінація: клацання по трею їх закриває.",
                de: "Dasselbe wie der Eintrag im Infobereichsmenü. Eine QuickInfo oder ein offenes Menü erfasst nur die Tastenkombination: Ein Klick auf den Infobereich schließt sie.",
                it: "Uguale alla voce del menu nell'area di notifica. Solo la combinazione cattura un suggerimento o un menu aperto: un clic sull'area di notifica li chiude.",
                es: "Lo mismo que la opción del menú de la bandeja. Solo la combinación captura una información sobre herramientas o un menú abierto: un clic en la bandeja los cierra.",
                fr: "Identique à l'entrée du menu de la zone de notification. Seule la combinaison capture une info-bulle ou un menu ouvert : un clic sur la zone de notification les ferme.",
                pt: "O mesmo que o item do menu da área de notificação. Só a combinação apanha uma dica ou um menu aberto: um clique na área de notificação fecha-os.",
                ar: "مثل عنصر قائمة منطقة الإشعارات. وحده الاختصار يلتقط تلميحًا أو قائمة مفتوحة: فالنقر على منطقة الإشعارات يغلقهما.",
                hi: "ट्रे मेनू के आइटम जैसा ही। खुला टूलटिप या मेनू सिर्फ़ संयोजन से पकड़ में आता है: ट्रे पर क्लिक उन्हें बंद कर देता है।",
                bn: "ট্রে মেনুর আইটেমের মতোই। খোলা টুলটিপ বা মেনু শুধু সমন্বয় দিয়েই ধরা যায়: ট্রেতে ক্লিক করলে সেগুলি বন্ধ হয়ে যায়।",
                ur: "ٹرے مینو کے آئٹم جیسا ہی۔ کھلا ٹول ٹپ یا مینو صرف مجموعے سے پکڑا جاتا ہے: ٹرے پر کلک انہیں بند کر دیتا ہے۔",
                zh: "与托盘菜单项相同。只有组合键能截到工具提示或打开的菜单：点击托盘会把它们关掉。");

            Add("Также сохранять снимки в папку",
                en: "Also save captures to a folder",
                uk: "Також зберігати знімки в папку",
                de: "Aufnahmen auch in einem Ordner speichern",
                it: "Salva le catture anche in una cartella",
                es: "Guardar también las capturas en una carpeta",
                fr: "Enregistrer aussi les captures dans un dossier",
                pt: "Guardar também as capturas numa pasta",
                ar: "حفظ اللقطات في مجلد أيضًا",
                hi: "स्क्रीनशॉट किसी फ़ोल्डर में भी सहेजें",
                bn: "স্ক্রিনশটগুলো একটি ফোল্ডারেও সংরক্ষণ করুন",
                ur: "اسکرین شاٹس کسی فولڈر میں بھی محفوظ کریں",
                zh: "同时将截图保存到文件夹");

            Add("По умолчанию выключено: снимок попадает только в буфер обмена. С флажком каждый выделенный фрагмент также сохраняется как PNG в папку ниже.",
                en: "Off by default: a capture goes to the clipboard only. With this on, every selected region is also saved as a PNG into the folder below.",
                uk: "За замовчуванням вимкнено: знімок потрапляє лише в буфер обміну. З прапорцем кожен виділений фрагмент також зберігається як PNG у папку нижче.",
                de: "Standardmäßig aus: Eine Aufnahme landet nur in der Zwischenablage. Ist dies eingeschaltet, wird jeder ausgewählte Ausschnitt zusätzlich als PNG im Ordner unten gespeichert.",
                it: "Disattivato per impostazione predefinita: la cattura va solo negli appunti. Se attivo, ogni area selezionata viene salvata anche come PNG nella cartella qui sotto.",
                es: "Desactivado de forma predeterminada: la captura va solo al portapapeles. Si se activa, cada zona seleccionada también se guarda como PNG en la carpeta de abajo.",
                fr: "Désactivé par défaut : la capture va uniquement dans le presse-papiers. Une fois activé, chaque zone sélectionnée est aussi enregistrée en PNG dans le dossier ci-dessous.",
                pt: "Desligado por predefinição: a captura vai apenas para a área de transferência. Com esta opção, cada área selecionada é também guardada como PNG na pasta abaixo.",
                ar: "متوقف افتراضيًا: تذهب اللقطة إلى الحافظة فقط. عند التفعيل يُحفَظ كل جزء محدد أيضًا بصيغة PNG في المجلد أدناه.",
                hi: "डिफ़ॉल्ट रूप से बंद: स्क्रीनशॉट सिर्फ़ क्लिपबोर्ड पर जाता है। इसे चालू करने पर हर चुना हुआ हिस्सा नीचे दिए फ़ोल्डर में PNG के रूप में भी सहेजा जाता है।",
                bn: "ডিফল্টভাবে বন্ধ: স্ক্রিনশট শুধু ক্লিপবোর্ডে যায়। চালু করলে প্রতিটি নির্বাচিত অংশ নিচের ফোল্ডারে PNG হিসেবেও সংরক্ষিত হয়।",
                ur: "طے شدہ طور پر بند: اسکرین شاٹ صرف کلپ بورڈ پر جاتا ہے۔ اسے فعال کرنے پر ہر منتخب حصہ نیچے والے فولڈر میں PNG کے طور پر بھی محفوظ ہوتا ہے۔",
                zh: "默认关闭：截图只进入剪贴板。开启后，每个选中的区域还会以 PNG 保存到下方的文件夹。");

            Add("Выбрать...",
                en: "Choose...",
                uk: "Вибрати...",
                de: "Auswählen...",
                it: "Scegli...",
                es: "Elegir...",
                fr: "Choisir...",
                pt: "Escolher...",
                ar: "اختيار...",
                hi: "चुनें...",
                bn: "বেছে নিন...",
                ur: "منتخب کریں...",
                zh: "选择...");

            Add("Открыть папку",
                en: "Open folder",
                uk: "Відкрити папку",
                de: "Ordner öffnen",
                it: "Apri cartella",
                es: "Abrir carpeta",
                fr: "Ouvrir le dossier",
                pt: "Abrir pasta",
                ar: "فتح المجلد",
                hi: "फ़ोल्डर खोलें",
                bn: "ফোল্ডার খুলুন",
                ur: "فولڈر کھولیں",
                zh: "打开文件夹");

            Add("Снимок всегда попадает в буфер обмена и не записывается в историю буфера. На диск он пишется, только если включено сохранение, и только выделенный фрагмент - в показанную папку (а если она недоступна - в «Изображения\\Снимки экрана» или «Загрузки», и CyrFlip сразу скажет, куда). Файлы не шифруются, CyrFlip их не удаляет и никуда не отправляет. Содержимое, которое защищает Windows (видео с DRM, окно UAC), получается чёрным.",
                en: "A capture always goes to the clipboard and is not recorded in the clipboard history. It is written to disk only while saving is on, and only the selected region - into the folder shown (or, when that folder is unreachable, into Pictures\\Screenshots or Downloads, and CyrFlip tells you which at once). The files are not encrypted; CyrFlip never deletes or sends them anywhere. Content Windows protects (DRM video, the UAC prompt) comes out black.",
                uk: "Знімок завжди потрапляє в буфер обміну і не записується в історію буфера. На диск він пишеться, лише якщо ввімкнено збереження, і лише виділений фрагмент - у показану папку (а якщо вона недоступна - у «Зображення\\Знімки екрана» або «Завантаження», і CyrFlip одразу скаже, куди). Файли не шифруються, CyrFlip їх не видаляє і нікуди не надсилає. Вміст, який захищає Windows (відео з DRM, вікно UAC), виходить чорним.",
                de: "Eine Aufnahme landet immer in der Zwischenablage und wird nicht im Zwischenablageverlauf gespeichert. Auf die Festplatte wird sie nur geschrieben, wenn das Speichern eingeschaltet ist, und nur der ausgewählte Ausschnitt - in den angezeigten Ordner (oder, wenn er nicht erreichbar ist, nach „Bilder\\Screenshots“ bzw. „Downloads“, und CyrFlip sagt sofort, wohin). Die Dateien werden nicht verschlüsselt; CyrFlip löscht sie nie und sendet sie nirgendwohin. Von Windows geschützte Inhalte (DRM-Video, das UAC-Fenster) erscheinen schwarz.",
                it: "La cattura va sempre negli appunti e non viene registrata nella cronologia degli appunti. Viene scritta su disco solo se il salvataggio è attivo, e solo l'area selezionata - nella cartella mostrata (oppure, se non è raggiungibile, in Immagini\\Screenshot o Download, e CyrFlip ti dice subito dove). I file non sono cifrati; CyrFlip non li elimina né li invia da nessuna parte. I contenuti protetti da Windows (video con DRM, la finestra UAC) risultano neri.",
                es: "La captura siempre va al portapapeles y no se registra en el historial del portapapeles. Solo se escribe en el disco si el guardado está activado, y solo la zona seleccionada: en la carpeta indicada (o, si no está disponible, en Imágenes\\Capturas de pantalla o Descargas, y CyrFlip le dice al instante dónde). Los archivos no se cifran; CyrFlip nunca los elimina ni los envía a ninguna parte. El contenido que protege Windows (vídeo con DRM, la ventana de UAC) sale en negro.",
                fr: "Une capture va toujours dans le presse-papiers et n'est pas enregistrée dans l'historique du presse-papiers. Elle n'est écrite sur le disque que si l'enregistrement est activé, et seulement la zone sélectionnée - dans le dossier affiché (ou, s'il est inaccessible, dans Images\\Captures d'écran ou Téléchargements, et CyrFlip vous dit aussitôt où). Les fichiers ne sont pas chiffrés ; CyrFlip ne les supprime jamais et ne les envoie nulle part. Le contenu protégé par Windows (vidéo avec DRM, la fenêtre UAC) sort en noir.",
                pt: "A captura vai sempre para a área de transferência e não é registada no histórico. Só é escrita no disco se a gravação estiver ligada, e apenas a área selecionada - na pasta indicada (ou, se esta não estiver acessível, em Imagens\\Capturas de ecrã ou Transferências, e o CyrFlip diz logo onde). Os ficheiros não são cifrados; o CyrFlip nunca os apaga nem os envia para lado nenhum. O conteúdo que o Windows protege (vídeo com DRM, a janela do UAC) sai a preto.",
                ar: "تذهب اللقطة دائمًا إلى الحافظة ولا تُسجَّل في سجل الحافظة. لا تُكتب على القرص إلا عند تفعيل الحفظ، والجزء المحدد فقط - في المجلد المعروض (أو، إذا تعذّر الوصول إليه، في «الصور\\لقطات الشاشة» أو «التنزيلات»، ويخبرك CyrFlip فورًا أين). الملفات غير مشفّرة، ولا يحذفها CyrFlip ولا يرسلها إلى أي مكان. المحتوى الذي يحميه Windows (فيديو DRM، نافذة UAC) يظهر أسود.",
                hi: "स्क्रीनशॉट हमेशा क्लिपबोर्ड पर जाता है और क्लिपबोर्ड इतिहास में दर्ज नहीं होता। डिस्क पर वह तभी लिखा जाता है जब सहेजना चालू हो, और केवल चुना हुआ हिस्सा - दिखाए गए फ़ोल्डर में (या, अगर वह उपलब्ध न हो, तो «चित्र\\स्क्रीनशॉट» या «डाउनलोड» में, और CyrFlip तुरंत बताता है कहाँ)। फ़ाइलें एन्क्रिप्ट नहीं होतीं; CyrFlip उन्हें न हटाता है, न कहीं भेजता है। Windows द्वारा संरक्षित सामग्री (DRM वीडियो, UAC विंडो) काली आती है।",
                bn: "স্ক্রিনশট সবসময় ক্লিপবোর্ডে যায় এবং ক্লিপবোর্ড ইতিহাসে লেখা হয় না। সংরক্ষণ চালু থাকলেই শুধু তা ডিস্কে লেখা হয়, আর শুধু নির্বাচিত অংশটি - দেখানো ফোল্ডারে (বা সেটি অপ্রাপ্য হলে «ছবি\\স্ক্রিনশট» বা «ডাউনলোড»-এ, আর CyrFlip সঙ্গে সঙ্গে জানায় কোথায়)। ফাইলগুলো এনক্রিপ্ট করা হয় না; CyrFlip সেগুলো মুছে ফেলে না বা কোথাও পাঠায় না। Windows যে বিষয়বস্তু সুরক্ষিত রাখে (DRM ভিডিও, UAC উইন্ডো) তা কালো আসে।",
                ur: "اسکرین شاٹ ہمیشہ کلپ بورڈ پر جاتا ہے اور کلپ بورڈ کی تاریخ میں درج نہیں ہوتا۔ ڈسک پر وہ صرف تب لکھا جاتا ہے جب محفوظ کرنا فعال ہو، اور صرف منتخب حصہ - دکھائے گئے فولڈر میں (یا، اگر وہ دستیاب نہ ہو، تو «تصاویر\\اسکرین شاٹس» یا «ڈاؤن لوڈز» میں، اور CyrFlip فوراً بتاتا ہے کہاں)۔ فائلیں خفیہ نہیں کی جاتیں؛ CyrFlip انہیں نہ حذف کرتا ہے نہ کہیں بھیجتا ہے۔ Windows کا محفوظ کردہ مواد (DRM ویڈیو، UAC ونڈو) سیاہ آتا ہے۔",
                zh: "截图总是进入剪贴板，且不会记入剪贴板历史。只有开启保存时才写入磁盘，而且只写选中的区域 - 写入所示文件夹（若该文件夹无法访问，则写入“图片\\屏幕截图”或“下载”，CyrFlip 会立即告诉您写到了哪里）。文件不加密；CyrFlip 从不删除它们，也不发送到任何地方。受 Windows 保护的内容（DRM 视频、UAC 窗口）截出来是黑色的。");

            Add("Папка для снимков области экрана",
                en: "Folder for screen region captures",
                uk: "Папка для знімків області екрана",
                de: "Ordner für Bildschirmausschnitte",
                it: "Cartella per le catture dello schermo",
                es: "Carpeta para las capturas de pantalla",
                fr: "Dossier des captures d'écran",
                pt: "Pasta para as capturas de ecrã",
                ar: "مجلد لقطات الشاشة",
                hi: "स्क्रीनशॉट के लिए फ़ोल्डर",
                bn: "স্ক্রিনশটের ফোল্ডার",
                ur: "اسکرین شاٹس کا فولڈر",
                zh: "屏幕区域截图的文件夹");

            Add("Этой папки пока нет - она появится при первом сохранённом снимке.",
                en: "This folder does not exist yet - it appears with the first saved capture.",
                uk: "Цієї папки ще немає - вона з'явиться з першим збереженим знімком.",
                de: "Diesen Ordner gibt es noch nicht - er entsteht mit der ersten gespeicherten Aufnahme.",
                it: "Questa cartella non esiste ancora: verrà creata con la prima cattura salvata.",
                es: "Esta carpeta aún no existe: aparecerá con la primera captura guardada.",
                fr: "Ce dossier n'existe pas encore : il apparaîtra avec la première capture enregistrée.",
                pt: "Esta pasta ainda não existe - aparece com a primeira captura guardada.",
                ar: "هذا المجلد غير موجود بعد - سيظهر مع أول لقطة محفوظة.",
                hi: "यह फ़ोल्डर अभी मौजूद नहीं है - पहला स्क्रीनशॉट सहेजने पर बनेगा।",
                bn: "এই ফোল্ডারটি এখনো নেই - প্রথম স্ক্রিনশট সংরক্ষণ করলে তৈরি হবে।",
                ur: "یہ فولڈر ابھی موجود نہیں - پہلا اسکرین شاٹ محفوظ ہونے پر بنے گا۔",
                zh: "此文件夹尚不存在 - 保存第一张截图时才会创建。");

            Add("Задать хоткей снимка области экрана",
                en: "Set the screen region capture hotkey",
                uk: "Задати хоткей знімка області екрана",
                de: "Tastenkombination für den Bildschirmausschnitt festlegen",
                it: "Imposta la scorciatoia per la cattura di un'area",
                es: "Definir el atajo de la captura de una zona",
                fr: "Définir le raccourci de la capture d'une zone",
                pt: "Definir o atalho da captura de uma área",
                ar: "تعيين اختصار لقطة جزء من الشاشة",
                hi: "स्क्रीन के हिस्से के स्क्रीनशॉट की हॉटकी सेट करें",
                bn: "স্ক্রিনের অংশের স্ক্রিনশটের হটকি সেট করুন",
                ur: "اسکرین کے حصے کے اسکرین شاٹ کی ہاٹ کی مقرر کریں",
                zh: "设置屏幕区域截图的快捷键");

            // ---- Balloons ----
            Add("Не удалось сделать снимок экрана.",
                en: "Could not capture the screen.",
                uk: "Не вдалося зробити знімок екрана.",
                de: "Der Bildschirm konnte nicht aufgenommen werden.",
                it: "Impossibile catturare lo schermo.",
                es: "No se pudo capturar la pantalla.",
                fr: "Impossible de capturer l'écran.",
                pt: "Não foi possível capturar o ecrã.",
                ar: "تعذّر التقاط الشاشة.",
                hi: "स्क्रीनशॉट नहीं लिया जा सका।",
                bn: "স্ক্রিনশট নেওয়া গেল না।",
                ur: "اسکرین شاٹ نہیں لیا جا سکا۔",
                zh: "无法截取屏幕。");

            Add("Не удалось положить снимок в буфер обмена - он занят другой программой. Повторите.",
                en: "Could not put the capture on the clipboard - another program holds it. Try again.",
                uk: "Не вдалося покласти знімок у буфер обміну - його зайняла інша програма. Повторіть.",
                de: "Die Aufnahme konnte nicht in die Zwischenablage gelegt werden - ein anderes Programm belegt sie. Versuchen Sie es erneut.",
                it: "Impossibile mettere la cattura negli appunti: li occupa un altro programma. Riprova.",
                es: "No se pudo poner la captura en el portapapeles: otro programa lo tiene ocupado. Vuelva a intentarlo.",
                fr: "Impossible de placer la capture dans le presse-papiers : un autre programme l'occupe. Réessayez.",
                pt: "Não foi possível pôr a captura na área de transferência - outro programa está a usá-la. Tente novamente.",
                ar: "تعذّر وضع اللقطة في الحافظة - إذ يشغلها برنامج آخر. أعد المحاولة.",
                hi: "स्क्रीनशॉट क्लिपबोर्ड पर नहीं रखा जा सका - उसे कोई दूसरा प्रोग्राम पकड़े है। फिर से कोशिश करें।",
                bn: "স্ক্রিনশট ক্লিপবোর্ডে রাখা গেল না - অন্য একটি প্রোগ্রাম সেটি ধরে রেখেছে। আবার চেষ্টা করুন।",
                ur: "اسکرین شاٹ کلپ بورڈ پر نہیں رکھا جا سکا - اسے کوئی اور پروگرام استعمال کر رہا ہے۔ دوبارہ کوشش کریں۔",
                zh: "无法把截图放入剪贴板 - 它被另一个程序占用。请重试。");

            Add("Папка для снимков недоступна - снимок сохранён сюда: {0}",
                en: "The capture folder is unreachable - the capture was saved here instead: {0}",
                uk: "Папка для знімків недоступна - знімок збережено сюди: {0}",
                de: "Der Ordner für Aufnahmen ist nicht erreichbar - die Aufnahme wurde stattdessen hier gespeichert: {0}",
                it: "La cartella delle catture non è raggiungibile: la cattura è stata salvata qui: {0}",
                es: "La carpeta de capturas no está disponible: la captura se guardó aquí: {0}",
                fr: "Le dossier des captures est inaccessible : la capture a été enregistrée ici : {0}",
                pt: "A pasta das capturas está inacessível - a captura foi guardada aqui: {0}",
                ar: "تعذّر الوصول إلى مجلد اللقطات - حُفظت اللقطة هنا بدلًا منه: {0}",
                hi: "स्क्रीनशॉट का फ़ोल्डर उपलब्ध नहीं है - स्क्रीनशॉट यहाँ सहेजा गया: {0}",
                bn: "স্ক্রিনশটের ফোল্ডার অপ্রাপ্য - স্ক্রিনশটটি এখানে সংরক্ষিত হয়েছে: {0}",
                ur: "اسکرین شاٹس کا فولڈر دستیاب نہیں - اسکرین شاٹ یہاں محفوظ کیا گیا: {0}",
                zh: "截图文件夹无法访问 - 截图已改存到这里：{0}");

            Add("Снимок в буфере обмена, но сохранить файл не удалось ни в одну папку.",
                en: "The capture is on the clipboard, but the file could not be saved into any folder.",
                uk: "Знімок у буфері обміну, але зберегти файл не вдалося в жодну папку.",
                de: "Die Aufnahme liegt in der Zwischenablage, aber die Datei konnte in keinem Ordner gespeichert werden.",
                it: "La cattura è negli appunti, ma non è stato possibile salvare il file in nessuna cartella.",
                es: "La captura está en el portapapeles, pero no se pudo guardar el archivo en ninguna carpeta.",
                fr: "La capture est dans le presse-papiers, mais le fichier n'a pu être enregistré dans aucun dossier.",
                pt: "A captura está na área de transferência, mas não foi possível guardar o ficheiro em nenhuma pasta.",
                ar: "اللقطة في الحافظة، لكن تعذّر حفظ الملف في أي مجلد.",
                hi: "स्क्रीनशॉट क्लिपबोर्ड पर है, पर फ़ाइल किसी भी फ़ोल्डर में सहेजी नहीं जा सकी।",
                bn: "স্ক্রিনশটটি ক্লিপবোর্ডে আছে, কিন্তু ফাইলটি কোনো ফোল্ডারেই সংরক্ষণ করা গেল না।",
                ur: "اسکرین شاٹ کلپ بورڈ پر ہے، لیکن فائل کسی بھی فولڈر میں محفوظ نہیں کی جا سکی۔",
                zh: "截图已在剪贴板中，但文件无法保存到任何文件夹。");
        }
    }
}
