namespace CyrFlip
{
    /// <summary>
    /// The built-in translator (a local Ollama server): the settings tab, the direction table, the
    /// result window near the cursor, the tray entry and every line of the Ollama status.
    /// </summary>
    internal static partial class Localization
    {
        private static void AddTranslateStrings()
        {
            // ---- Tab, master switch and the Ollama block ----
            Add("Перевод",
                en: "Translation",
                uk: "Переклад",
                de: "Übersetzung",
                it: "Traduzione",
                es: "Traducción",
                fr: "Traduction",
                pt: "Tradução",
                ar: "الترجمة",
                hi: "अनुवाद",
                bn: "অনুবাদ",
                ur: "ترجمہ",
                zh: "翻译");

            Add("Перевод выделенного текста локальной моделью Ollama: текст никуда не отправляется, кроме сервера, указанного ниже (по умолчанию это ваш же компьютер). Сам Ollama и языковую модель нужно установить один раз — кнопками ниже.",
                en: "Translate the selected text with a local Ollama model: the text goes nowhere except the server below, which is your own computer by default. Ollama itself and a language model have to be installed once, with the buttons below.",
                uk: "Переклад виділеного тексту локальною моделлю Ollama: текст нікуди не надсилається, окрім сервера, указаного нижче (за замовчуванням це ваш же комп'ютер). Сам Ollama і мовну модель потрібно встановити один раз — кнопками нижче.",
                de: "Übersetzung des ausgewählten Textes durch ein lokales Ollama-Modell: Der Text wird an nichts anderes gesendet als an den unten angegebenen Server (standardmäßig ist das Ihr eigener Computer). Ollama selbst und das Sprachmodell müssen Sie einmalig installieren — mit den Schaltflächen unten.",
                it: "Traduzione del testo selezionato con un modello Ollama locale: il testo non viene inviato da nessuna parte, tranne che al server indicato qui sotto (per impostazione predefinita è il tuo computer). Ollama e il modello linguistico vanno installati una volta sola, con i pulsanti qui sotto.",
                es: "Traducción del texto seleccionado con un modelo local de Ollama: el texto no se envía a ninguna parte, salvo al servidor indicado más abajo (de forma predeterminada, su propio equipo). Ollama y el modelo de lenguaje se instalan una sola vez, con los botones de abajo.",
                fr: "Traduction du texte sélectionné par un modèle Ollama local : le texte n'est envoyé nulle part, sauf au serveur indiqué ci-dessous (par défaut, votre propre ordinateur). Ollama lui-même et le modèle de langue doivent être installés une seule fois, à l'aide des boutons ci-dessous.",
                pt: "Tradução do texto selecionado com um modelo Ollama local: o texto não é enviado para lado nenhum além do servidor indicado abaixo (que, por predefinição, é o seu próprio computador). O Ollama e o modelo de linguagem têm de ser instalados uma vez, com os botões abaixo.",
                ar: "ترجمة النص المحدد بواسطة نموذج Ollama محلي: لا يُرسَل النص إلى أي جهة سوى الخادم المحدَّد أدناه (وهو جهازك نفسه افتراضيًا). يجب تثبيت Ollama والنموذج اللغوي مرة واحدة فقط — عبر الأزرار أدناه.",
                hi: "स्थानीय Ollama मॉडल से चयनित टेक्स्ट का अनुवाद: टेक्स्ट नीचे बताए गए सर्वर के अलावा कहीं नहीं भेजा जाता (डिफ़ॉल्ट रूप से यह आपका अपना कंप्यूटर ही है)। Ollama और भाषा मॉडल को एक बार इंस्टॉल करना होता है — नीचे दिए गए बटनों से।",
                bn: "স্থানীয় Ollama মডেল দিয়ে নির্বাচিত লেখার অনুবাদ: লেখাটি নিচে উল্লিখিত সার্ভার ছাড়া আর কোথাও পাঠানো হয় না (ডিফল্টভাবে সেটি আপনার নিজের কম্পিউটারই)। Ollama এবং ভাষা মডেল একবার ইনস্টল করে নিতে হবে — নিচের বোতামগুলি দিয়ে।",
                ur: "منتخب متن کا ترجمہ مقامی Ollama ماڈل کے ذریعے: متن نیچے دیے گئے سرور کے علاوہ کہیں نہیں بھیجا جاتا (طے شدہ طور پر یہ آپ ہی کا کمپیوٹر ہے)۔ Ollama اور زبان کا ماڈل ایک بار انسٹال کرنے ہوتے ہیں — نیچے دیے گئے بٹنوں سے۔",
                zh: "使用本地 Ollama 模型翻译选中的文本：文本不会发送到别处，只会发往下方指定的服务器（默认就是您自己的电脑）。Ollama 本身和语言模型需要用下方的按钮安装一次。");

            Add("Включить перевод выделенного текста",
                en: "Enable translation of the selected text",
                uk: "Увімкнути переклад виділеного тексту",
                de: "Übersetzung des ausgewählten Textes aktivieren",
                it: "Attiva la traduzione del testo selezionato",
                es: "Activar la traducción del texto seleccionado",
                fr: "Activer la traduction du texte sélectionné",
                pt: "Ativar a tradução do texto selecionado",
                ar: "تفعيل ترجمة النص المحدد",
                hi: "चयनित टेक्स्ट का अनुवाद चालू करें",
                bn: "নির্বাচিত লেখার অনুবাদ চালু করুন",
                ur: "منتخب متن کا ترجمہ فعال کریں",
                zh: "启用选中文本的翻译");

            Add("Пока выключено, комбинации перевода не назначены, в трее нет пункта перевода и CyrFlip не открывает ни одного сетевого соединения.",
                en: "While this is off no translation chord is bound, the tray has no translate entry, and CyrFlip opens no network connection at all.",
                uk: "Поки вимкнено, комбінації перекладу не призначені, у треї немає пункту перекладу, і CyrFlip не відкриває жодного мережевого з'єднання.",
                de: "Solange dies ausgeschaltet ist, sind keine Übersetzungskombinationen zugewiesen, im Infobereich gibt es keinen Übersetzungseintrag und CyrFlip öffnet keine einzige Netzwerkverbindung.",
                it: "Finché è disattivata, non viene assegnata alcuna combinazione per la traduzione, l'area di notifica non mostra la voce di traduzione e CyrFlip non apre alcuna connessione di rete.",
                es: "Mientras esté desactivado, no se asigna ninguna combinación de traducción, el menú de la bandeja no muestra la opción de traducir y CyrFlip no abre ninguna conexión de red.",
                fr: "Tant que l'option est désactivée, aucune combinaison de traduction n'est attribuée, la zone de notification n'affiche aucune entrée de traduction et CyrFlip n'ouvre aucune connexion réseau.",
                pt: "Enquanto estiver desativado, não há combinações de teclas atribuídas à tradução, o menu da área de notificação não tem o item de tradução e o CyrFlip não abre qualquer ligação de rede.",
                ar: "أثناء الإيقاف لا تُعيَّن أي اختصارات للترجمة، ولا يظهر عنصر الترجمة في منطقة الإشعارات، ولا يفتح CyrFlip أي اتصال بالشبكة.",
                hi: "जब तक यह बंद है, अनुवाद के लिए कोई कुंजी संयोजन असाइन नहीं होता, ट्रे में अनुवाद का विकल्प नहीं दिखता और CyrFlip एक भी नेटवर्क कनेक्शन नहीं खोलता।",
                bn: "বন্ধ থাকা অবস্থায় অনুবাদের কোনো শর্টকাট নির্ধারিত হয় না, ট্রেতে অনুবাদের কোনো আইটেম থাকে না এবং CyrFlip একটিও নেটওয়ার্ক সংযোগ খোলে না।",
                ur: "جب تک یہ بند ہے، ترجمے کا کوئی کلیدی مجموعہ مقرر نہیں ہوتا، ٹرے مینو میں ترجمے کا کوئی اندراج نہیں آتا اور CyrFlip کوئی نیٹ ورک کنکشن نہیں کھولتا۔",
                zh: "关闭时不会分配任何翻译组合键，托盘中不会出现翻译菜单项，CyrFlip 也不会建立任何网络连接。");

            Add("Адрес сервера:",
                en: "Server address:",
                uk: "Адреса сервера:",
                de: "Serveradresse:",
                it: "Indirizzo del server:",
                es: "Dirección del servidor:",
                fr: "Adresse du serveur :",
                pt: "Endereço do servidor:",
                ar: "عنوان الخادم:",
                hi: "सर्वर का पता:",
                bn: "সার্ভারের ঠিকানা:",
                ur: "سرور کا پتہ:",
                zh: "服务器地址：");

            Add("Пусто — http://localhost:11434, то есть Ollama на этом компьютере. Если указать другой адрес, выделенный текст будет отправлен на ту машину.",
                en: "Empty means http://localhost:11434, that is Ollama on this computer. Enter another address and the selected text will be sent to that machine.",
                uk: "Порожньо — http://localhost:11434, тобто Ollama на цьому комп'ютері. Якщо вказати іншу адресу, виділений текст буде надіслано на ту машину.",
                de: "Leer bedeutet http://localhost:11434, also Ollama auf diesem Computer. Geben Sie eine andere Adresse an, wird der ausgewählte Text an jenen Rechner gesendet.",
                it: "Vuoto significa http://localhost:11434, cioè Ollama su questo computer. Se indichi un altro indirizzo, il testo selezionato verrà inviato a quella macchina.",
                es: "Vacío significa http://localhost:11434, es decir, Ollama en este equipo. Si indica otra dirección, el texto seleccionado se enviará a esa máquina.",
                fr: "Vide signifie http://localhost:11434, c'est-à-dire Ollama sur cet ordinateur. Si vous indiquez une autre adresse, le texte sélectionné sera envoyé à cette machine.",
                pt: "Vazio significa http://localhost:11434, ou seja, o Ollama neste computador. Se indicar outro endereço, o texto selecionado será enviado para essa máquina.",
                ar: "الحقل الفارغ يعني http://localhost:11434، أي Ollama على هذا الجهاز. وإذا أدخلت عنوانًا آخر، فسيُرسَل النص المحدد إلى ذلك الجهاز.",
                hi: "खाली छोड़ने पर http://localhost:11434, यानी इसी कंप्यूटर पर चल रहा Ollama। कोई दूसरा पता देने पर चयनित टेक्स्ट उस मशीन को भेजा जाएगा।",
                bn: "ফাঁকা রাখলে http://localhost:11434, অর্থাৎ এই কম্পিউটারের Ollama। অন্য ঠিকানা দিলে নির্বাচিত লেখা সেই মেশিনে পাঠানো হবে।",
                ur: "خالی چھوڑنے کا مطلب http://localhost:11434 ہے، یعنی اسی کمپیوٹر پر موجود Ollama۔ کوئی دوسرا پتہ درج کرنے پر منتخب متن اُسی مشین کو بھیجا جائے گا۔",
                zh: "留空表示 http://localhost:11434，即本机上的 Ollama。如果填写其他地址，选中的文本就会被发送到那台机器。");

            Add("Модель:",
                en: "Model:",
                uk: "Модель:",
                de: "Modell:",
                it: "Modello:",
                es: "Modelo:",
                fr: "Modèle :",
                pt: "Modelo:",
                ar: "النموذج:",
                hi: "मॉडल:",
                bn: "মডেল:",
                ur: "ماڈل:",
                zh: "模型：");

            Add("Загрузить модель",
                en: "Download the model",
                uk: "Завантажити модель",
                de: "Modell herunterladen",
                it: "Scarica il modello",
                es: "Descargar modelo",
                fr: "Télécharger le modèle",
                pt: "Transferir modelo",
                ar: "تنزيل النموذج",
                hi: "मॉडल डाउनलोड करें",
                bn: "মডেল ডাউনলোড করুন",
                ur: "ماڈل ڈاؤن لوڈ کریں",
                zh: "下载模型");

            Add("Рекомендуемые: qwen2.5:3b (~2 ГБ, по умолчанию), gemma2:2b (~1,6 ГБ, для слабых машин), llama3.2:3b (~2 ГБ), aya-expanse:8b (~5 ГБ, заметно лучше переводит, нужно от 8 ГБ ОЗУ). Модель занимает память процесса Ollama, а не CyrFlip.",
                en: "Recommended: qwen2.5:3b (~2 GB, the default), gemma2:2b (~1.6 GB, for weaker machines), llama3.2:3b (~2 GB), aya-expanse:8b (~5 GB, translates noticeably better, needs 8 GB of RAM or more). The model occupies the memory of the Ollama process, not of CyrFlip.",
                uk: "Рекомендовані: qwen2.5:3b (~2 ГБ, за замовчуванням), gemma2:2b (~1,6 ГБ, для слабких машин), llama3.2:3b (~2 ГБ), aya-expanse:8b (~5 ГБ, помітно краще перекладає, потрібно від 8 ГБ ОЗП). Модель займає пам'ять процесу Ollama, а не CyrFlip.",
                de: "Empfohlen: qwen2.5:3b (~2 GB, Standard), gemma2:2b (~1,6 GB, für schwächere Rechner), llama3.2:3b (~2 GB), aya-expanse:8b (~5 GB, übersetzt merklich besser, benötigt mindestens 8 GB RAM). Das Modell belegt den Speicher des Ollama-Prozesses, nicht den von CyrFlip.",
                it: "Consigliati: qwen2.5:3b (~2 GB, predefinito), gemma2:2b (~1,6 GB, per macchine poco potenti), llama3.2:3b (~2 GB), aya-expanse:8b (~5 GB, traduce nettamente meglio, richiede almeno 8 GB di RAM). Il modello occupa la memoria del processo Ollama, non quella di CyrFlip.",
                es: "Recomendados: qwen2.5:3b (~2 GB, el predeterminado), gemma2:2b (~1,6 GB, para equipos poco potentes), llama3.2:3b (~2 GB), aya-expanse:8b (~5 GB, traduce bastante mejor, necesita 8 GB de RAM o más). El modelo ocupa la memoria del proceso de Ollama, no la de CyrFlip.",
                fr: "Recommandés : qwen2.5:3b (~2 Go, par défaut), gemma2:2b (~1,6 Go, pour les machines modestes), llama3.2:3b (~2 Go), aya-expanse:8b (~5 Go, traduit nettement mieux, nécessite au moins 8 Go de RAM). Le modèle occupe la mémoire du processus Ollama, pas celle de CyrFlip.",
                pt: "Recomendados: qwen2.5:3b (~2 GB, predefinido), gemma2:2b (~1,6 GB, para máquinas menos potentes), llama3.2:3b (~2 GB), aya-expanse:8b (~5 GB, traduz bastante melhor, precisa de 8 GB de RAM ou mais). O modelo ocupa a memória do processo do Ollama, não a do CyrFlip.",
                ar: "المُوصى بها: qwen2.5:3b (~2 غ.ب، الافتراضي)، gemma2:2b (~1.6 غ.ب، للأجهزة الضعيفة)، llama3.2:3b (~2 غ.ب)، aya-expanse:8b (~5 غ.ب، ترجمته أفضل بوضوح، ويحتاج 8 غ.ب من الذاكرة العشوائية على الأقل). يشغل النموذج ذاكرة عملية Ollama، لا ذاكرة CyrFlip.",
                hi: "अनुशंसित: qwen2.5:3b (~2 जीबी, डिफ़ॉल्ट), gemma2:2b (~1.6 जीबी, कमज़ोर मशीनों के लिए), llama3.2:3b (~2 जीबी), aya-expanse:8b (~5 जीबी, अनुवाद काफ़ी बेहतर करता है, कम से कम 8 जीबी रैम चाहिए)। मॉडल Ollama प्रोसेस की मेमोरी घेरता है, CyrFlip की नहीं।",
                bn: "প্রস্তাবিত: qwen2.5:3b (~2 জিবি, ডিফল্ট), gemma2:2b (~1.6 জিবি, দুর্বল মেশিনের জন্য), llama3.2:3b (~2 জিবি), aya-expanse:8b (~5 জিবি, লক্ষণীয়ভাবে ভালো অনুবাদ করে, কমপক্ষে 8 জিবি র‍্যাম প্রয়োজন)। মডেলটি CyrFlip-এর নয়, Ollama প্রসেসের মেমরি দখল করে।",
                ur: "تجویز کردہ: qwen2.5:3b (~2 جی بی، طے شدہ)، gemma2:2b (~1.6 جی بی، کم طاقت والی مشینوں کے لیے)، llama3.2:3b (~2 جی بی)، aya-expanse:8b (~5 جی بی، ترجمہ نمایاں طور پر بہتر کرتا ہے، کم از کم 8 جی بی ریم درکار ہے)۔ ماڈل Ollama کے پروسیس کی میموری گھیرتا ہے، CyrFlip کی نہیں۔",
                zh: "推荐：qwen2.5:3b（约 2 GB，默认）、gemma2:2b（约 1.6 GB，适合配置较低的电脑）、llama3.2:3b（约 2 GB）、aya-expanse:8b（约 5 GB，翻译效果明显更好，需要 8 GB 以上内存）。模型占用的是 Ollama 进程的内存，而不是 CyrFlip 的内存。");

            Add("Установить Ollama",
                en: "Install Ollama",
                uk: "Встановити Ollama",
                de: "Ollama installieren",
                it: "Installa Ollama",
                es: "Instalar Ollama",
                fr: "Installer Ollama",
                pt: "Instalar o Ollama",
                ar: "تثبيت Ollama",
                hi: "Ollama इंस्टॉल करें",
                bn: "Ollama ইনস্টল করুন",
                ur: "Ollama انسٹال کریں",
                zh: "安装 Ollama");

            Add("Запустить Ollama",
                en: "Start Ollama",
                uk: "Запустити Ollama",
                de: "Ollama starten",
                it: "Avvia Ollama",
                es: "Iniciar Ollama",
                fr: "Démarrer Ollama",
                pt: "Iniciar o Ollama",
                ar: "تشغيل Ollama",
                hi: "Ollama शुरू करें",
                bn: "Ollama চালু করুন",
                ur: "Ollama چلائیں",
                zh: "启动 Ollama");

            Add("Проверить связь",
                en: "Check the connection",
                uk: "Перевірити зв'язок",
                de: "Verbindung prüfen",
                it: "Verifica la connessione",
                es: "Comprobar conexión",
                fr: "Tester la connexion",
                pt: "Verificar a ligação",
                ar: "اختبار الاتصال",
                hi: "कनेक्शन जाँचें",
                bn: "সংযোগ পরীক্ষা করুন",
                ur: "کنکشن جانچیں",
                zh: "检查连接");

            Add("Запускать Ollama автоматически при переводе",
                en: "Start Ollama automatically when translating",
                uk: "Запускати Ollama автоматично під час перекладу",
                de: "Ollama beim Übersetzen automatisch starten",
                it: "Avvia Ollama automaticamente al momento della traduzione",
                es: "Iniciar Ollama automáticamente al traducir",
                fr: "Démarrer Ollama automatiquement lors d'une traduction",
                pt: "Iniciar o Ollama automaticamente ao traduzir",
                ar: "تشغيل Ollama تلقائيًا عند الترجمة",
                hi: "अनुवाद के समय Ollama अपने आप शुरू करें",
                bn: "অনুবাদের সময় Ollama স্বয়ংক্রিয়ভাবে চালু করুন",
                ur: "ترجمے کے وقت Ollama خودکار طور پر چلائیں",
                zh: "翻译时自动启动 Ollama");

            Add("Если сервер не отвечает в момент перевода, CyrFlip один раз попробует запустить его сам и подождёт до восьми секунд.",
                en: "If the server does not answer when a translation starts, CyrFlip tries to start it once and waits up to eight seconds.",
                uk: "Якщо сервер не відповідає в момент перекладу, CyrFlip один раз спробує запустити його сам і зачекає до восьми секунд.",
                de: "Antwortet der Server im Moment der Übersetzung nicht, versucht CyrFlip einmal, ihn selbst zu starten, und wartet bis zu acht Sekunden.",
                it: "Se il server non risponde quando parte una traduzione, CyrFlip proverà una volta ad avviarlo da sé e attenderà fino a otto secondi.",
                es: "Si el servidor no responde en el momento de traducir, CyrFlip intentará iniciarlo una vez y esperará hasta ocho segundos.",
                fr: "Si le serveur ne répond pas au moment de la traduction, CyrFlip essaie de le démarrer une fois et attend jusqu'à huit secondes.",
                pt: "Se o servidor não responder no momento da tradução, o CyrFlip tenta iniciá-lo uma vez e aguarda até oito segundos.",
                ar: "إذا لم يستجب الخادم عند بدء الترجمة، فسيحاول CyrFlip تشغيله بنفسه مرة واحدة وينتظر حتى ثماني ثوانٍ.",
                hi: "अगर अनुवाद शुरू होते समय सर्वर जवाब नहीं देता, तो CyrFlip एक बार उसे खुद शुरू करने की कोशिश करेगा और आठ सेकंड तक प्रतीक्षा करेगा।",
                bn: "অনুবাদ শুরুর সময় সার্ভার সাড়া না দিলে CyrFlip একবার নিজেই সেটি চালু করার চেষ্টা করবে এবং আট সেকেন্ড পর্যন্ত অপেক্ষা করবে।",
                ur: "اگر ترجمے کے وقت سرور جواب نہ دے تو CyrFlip ایک بار خود اسے چلانے کی کوشش کرے گا اور آٹھ سیکنڈ تک انتظار کرے گا۔",
                zh: "如果开始翻译时服务器没有响应，CyrFlip 会自行尝试启动一次，并最多等待八秒。");

            Add("Держать модель в памяти (мин):",
                en: "Keep the model in memory (min):",
                uk: "Тримати модель у пам'яті (хв):",
                de: "Modell im Speicher halten (Min.):",
                it: "Mantieni il modello in memoria (min):",
                es: "Mantener el modelo en memoria (min):",
                fr: "Garder le modèle en mémoire (min) :",
                pt: "Manter o modelo em memória (min):",
                ar: "إبقاء النموذج في الذاكرة (د):",
                hi: "मॉडल को मेमोरी में रखें (मिनट):",
                bn: "মেমরিতে মডেল ধরে রাখুন (মিনিট):",
                ur: "ماڈل کو میموری میں رکھیں (منٹ):",
                zh: "保持模型驻留内存（分钟）：");

            Add("Сколько Ollama держит модель загруженной после перевода. Больше — следующий перевод почти мгновенный, но несколько гигабайт памяти заняты. 0 — выгружать сразу.",
                en: "How long Ollama keeps the model loaded after a translation. A larger value makes the next translation nearly instant but keeps several gigabytes of memory in use. 0 unloads it at once.",
                uk: "Скільки Ollama тримає модель завантаженою після перекладу. Більше — наступний переклад майже миттєвий, але кілька гігабайтів пам'яті зайнято. 0 — вивантажувати одразу.",
                de: "Wie lange Ollama das Modell nach einer Übersetzung geladen lässt. Ein höherer Wert macht die nächste Übersetzung nahezu sofort, belegt aber mehrere Gigabyte Arbeitsspeicher. 0 entlädt es sofort.",
                it: "Per quanto tempo Ollama tiene il modello caricato dopo una traduzione. Un valore più alto rende la traduzione successiva quasi immediata, ma tiene occupati diversi gigabyte di memoria. 0 lo scarica subito.",
                es: "Cuánto tiempo mantiene Ollama el modelo cargado después de una traducción. Cuanto mayor sea el valor, más inmediata será la siguiente traducción, pero varios gigabytes de memoria seguirán ocupados. 0: liberarlo de inmediato.",
                fr: "Durée pendant laquelle Ollama garde le modèle chargé après une traduction. Plus la valeur est élevée, plus la traduction suivante est rapide, presque instantanée, mais plusieurs gigaoctets de mémoire restent occupés. 0 décharge le modèle immédiatement.",
                pt: "Durante quanto tempo o Ollama mantém o modelo carregado depois de uma tradução. Um valor maior torna a tradução seguinte quase instantânea, mas mantém vários gigabytes de memória ocupados. Com 0, o modelo é libertado de imediato.",
                ar: "المدة التي يُبقي فيها Ollama النموذج محمَّلًا بعد الترجمة. القيمة الأكبر تجعل الترجمة التالية شبه فورية، لكنها تُبقي عدة غيغابايتات من الذاكرة مشغولة. والقيمة 0 تعني تفريغه فورًا.",
                hi: "अनुवाद के बाद Ollama मॉडल को कितनी देर लोड रखे। ज़्यादा मान से अगला अनुवाद लगभग तुरंत होता है, पर कई गीगाबाइट मेमोरी घिरी रहती है। 0 का मतलब है उसे तुरंत मेमोरी से हटा देना।",
                bn: "অনুবাদের পর Ollama কত সময় মডেলটি লোড করা অবস্থায় রাখবে। মান বেশি হলে পরের অনুবাদ প্রায় সঙ্গে সঙ্গেই হয়, তবে কয়েক গিগাবাইট মেমরি দখল হয়ে থাকে। 0 দিলে সঙ্গে সঙ্গে আনলোড করা হয়।",
                ur: "ترجمے کے بعد Ollama ماڈل کو کتنی دیر لوڈ رکھے۔ زیادہ قدر سے اگلا ترجمہ تقریباً فوری ہو جاتا ہے، مگر کئی جی بی میموری گھری رہتی ہے۔ 0 کا مطلب فوراً اَن لوڈ کرنا ہے۔",
                zh: "翻译完成后 Ollama 保持模型加载的时长。数值越大，下一次翻译几乎瞬间完成，但会一直占用数 GB 内存。设为 0 则立即卸载。");

            Add("Ждать ответа не дольше (с):",
                en: "Wait for an answer no longer than (s):",
                uk: "Чекати на відповідь не довше (с):",
                de: "Maximale Wartezeit auf Antwort (Sek.):",
                it: "Attendi la risposta al massimo (s):",
                es: "Esperar la respuesta como máximo (s):",
                fr: "Attendre la réponse au maximum (s) :",
                pt: "Esperar pela resposta no máximo (s):",
                ar: "مهلة انتظار الرد (ث):",
                hi: "जवाब के लिए अधिकतम प्रतीक्षा (सेकंड):",
                bn: "উত্তরের জন্য সর্বোচ্চ অপেক্ষা (সেকেন্ড):",
                ur: "جواب کا زیادہ سے زیادہ انتظار (سیکنڈ):",
                zh: "响应等待上限（秒）：");

            Add("Если модель не ответила за это время, перевод прерывается и окно предлагает повторить.",
                en: "If the model has not answered within this time the translation is aborted and the window offers to try again.",
                uk: "Якщо модель не відповіла за цей час, переклад переривається, і вікно пропонує повторити.",
                de: "Antwortet das Modell nicht innerhalb dieser Zeit, wird die Übersetzung abgebrochen und das Fenster bietet einen neuen Versuch an.",
                it: "Se il modello non risponde entro questo tempo, la traduzione viene interrotta e la finestra propone di riprovare.",
                es: "Si el modelo no responde en ese tiempo, la traducción se interrumpe y la ventana ofrece repetirla.",
                fr: "Si le modèle n'a pas répondu dans ce délai, la traduction est interrompue et la fenêtre propose de réessayer.",
                pt: "Se o modelo não responder dentro deste tempo, a tradução é interrompida e a janela propõe tentar de novo.",
                ar: "إذا لم يرد النموذج خلال هذه المدة، تتوقف الترجمة وتعرض نافذة النتيجة إعادة المحاولة.",
                hi: "अगर मॉडल इतने समय में जवाब नहीं देता, तो अनुवाद रोक दिया जाता है और विंडो दोबारा कोशिश करने का विकल्प देती है।",
                bn: "এই সময়ের মধ্যে মডেল উত্তর না দিলে অনুবাদ বাতিল হয় এবং উইন্ডোটি আবার চেষ্টা করার প্রস্তাব দেয়।",
                ur: "اگر ماڈل نے اس دوران جواب نہ دیا تو ترجمہ روک دیا جاتا ہے اور ونڈو دوبارہ کوشش کرنے کی پیشکش کرتی ہے۔",
                zh: "如果模型在此时间内没有响应，翻译将中止，窗口会提示您重试。");

            Add("Направления перевода",
                en: "Translation directions",
                uk: "Напрямки перекладу",
                de: "Übersetzungsrichtungen",
                it: "Direzioni di traduzione",
                es: "Direcciones de traducción",
                fr: "Sens de traduction",
                pt: "Direções de tradução",
                ar: "اتجاهات الترجمة",
                hi: "अनुवाद की दिशाएँ",
                bn: "অনুবাদের দিক",
                ur: "ترجمے کی سمتیں",
                zh: "翻译方向");

            Add("Добавить направление...",
                en: "Add a direction...",
                uk: "Додати напрямок...",
                de: "Richtung hinzufügen...",
                it: "Aggiungi direzione...",
                es: "Añadir dirección...",
                fr: "Ajouter un sens de traduction...",
                pt: "Adicionar direção...",
                ar: "إضافة اتجاه...",
                hi: "दिशा जोड़ें...",
                bn: "দিক যোগ করুন...",
                ur: "سمت شامل کریں...",
                zh: "添加方向...");

            Add("«Язык интерфейса» и «Язык активной раскладки» вычисляются в момент нажатия. Одну комбинацию нельзя отдать двум действиям CyrFlip.",
                en: "\"Interface language\" and \"Active layout language\" are resolved at the moment the chord is pressed. One chord cannot be given to two CyrFlip actions.",
                uk: "«Мова інтерфейсу» та «Мова активної розкладки» визначаються в момент натискання. Одну комбінацію не можна віддати двом діям CyrFlip.",
                de: "«Oberflächensprache» und «Sprache des aktiven Layouts» werden im Moment des Tastendrucks ermittelt. Eine Kombination lässt sich nicht zwei CyrFlip-Aktionen zuweisen.",
                it: "«Lingua dell'interfaccia» e «Lingua del layout attivo» vengono determinate nel momento in cui premi la combinazione. Una stessa combinazione non può essere assegnata a due azioni di CyrFlip.",
                es: "«Idioma de la interfaz» e «Idioma de la distribución activa» se determinan en el momento de pulsar la combinación. Una misma combinación no puede asignarse a dos acciones de CyrFlip.",
                fr: "« Langue de l'interface » et « Langue de la disposition active » sont déterminées au moment où la combinaison est pressée. Une même combinaison ne peut pas être attribuée à deux actions de CyrFlip.",
                pt: "«Idioma da interface» e «Idioma do esquema de teclado ativo» são determinados no momento em que a combinação é premida. A mesma combinação não pode ser atribuída a duas ações do CyrFlip.",
                ar: "يُحدَّد «لغة الواجهة» و«لغة تخطيط لوحة المفاتيح النشط» لحظة الضغط على الاختصار. ولا يمكن إسناد اختصار واحد إلى إجراءين من إجراءات CyrFlip.",
                hi: "“इंटरफ़ेस की भाषा” और “सक्रिय लेआउट की भाषा” कुंजी दबाने के समय तय होती हैं। एक ही कुंजी संयोजन CyrFlip की दो क्रियाओं को नहीं दिया जा सकता।",
                bn: "“ইন্টারফেসের ভাষা” এবং “সক্রিয় লেআউটের ভাষা” শর্টকাট চাপার মুহূর্তে নির্ধারিত হয়। একই শর্টকাট CyrFlip-এর দুটি কাজে দেওয়া যায় না।",
                ur: "”انٹرفیس کی زبان“ اور ”فعال لے آؤٹ کی زبان“ کا تعین کلید دبانے کے لمحے ہوتا ہے۔ ایک ہی کلیدی مجموعہ CyrFlip کے دو کاموں کو نہیں دیا جا سکتا۔",
                zh: "「界面语言」和「当前键盘布局语言」在按下组合键的瞬间确定。同一个组合键不能分配给 CyrFlip 的两个操作。");

            Add("Результат",
                en: "Result",
                uk: "Результат",
                de: "Ergebnis",
                it: "Risultato",
                es: "Resultado",
                fr: "Résultat",
                pt: "Resultado",
                ar: "النتيجة",
                hi: "परिणाम",
                bn: "ফলাফল",
                ur: "نتیجہ",
                zh: "结果");

            Add("Класть перевод в буфер обмена",
                en: "Put the translation on the clipboard",
                uk: "Класти переклад у буфер обміну",
                de: "Übersetzung in die Zwischenablage legen",
                it: "Copia la traduzione negli appunti",
                es: "Copiar la traducción al portapapeles",
                fr: "Placer la traduction dans le presse-papiers",
                pt: "Colocar a tradução na área de transferência",
                ar: "وضع الترجمة في الحافظة",
                hi: "अनुवाद को क्लिपबोर्ड पर रखें",
                bn: "অনুবাদ ক্লিপবোর্ডে রাখুন",
                ur: "ترجمہ کلپ بورڈ میں رکھیں",
                zh: "将翻译放入剪贴板");

            Add("Перевод попадает в буфер обмена обычной записью — и, если история включена, сохраняется в ней, как любое другое копирование.",
                en: "The translation lands on the clipboard as an ordinary entry and, when the history is on, is stored there like any other copy.",
                uk: "Переклад потрапляє в буфер обміну звичайним записом — і, якщо історію ввімкнено, зберігається в ній, як будь-яке інше копіювання.",
                de: "Die Übersetzung landet als gewöhnlicher Eintrag in der Zwischenablage — und wird, wenn der Verlauf aktiv ist, dort wie jeder andere Kopiervorgang gespeichert.",
                it: "La traduzione finisce negli appunti come una voce qualsiasi e, se la cronologia è attiva, vi resta salvata come qualunque altra copia.",
                es: "La traducción llega al portapapeles como una entrada normal y, si el historial está activado, se guarda en él como cualquier otra copia.",
                fr: "La traduction est placée dans le presse-papiers comme une entrée ordinaire et, si l'historique est activé, y est conservée comme n'importe quelle autre copie.",
                pt: "A tradução entra na área de transferência como uma entrada normal e, se o histórico estiver ativado, fica lá guardada como qualquer outra cópia.",
                ar: "تُوضع الترجمة في الحافظة كأي إدخال عادي، وتُحفظ في السجل مثل أي عملية نسخ أخرى إذا كان السجل مفعَّلًا.",
                hi: "अनुवाद एक सामान्य प्रविष्टि की तरह क्लिपबोर्ड पर आता है — और अगर इतिहास चालू है, तो किसी भी अन्य कॉपी की तरह उसमें सहेजा जाता है।",
                bn: "অনুবাদটি সাধারণ এন্ট্রি হিসেবে ক্লিপবোর্ডে যায় এবং ইতিহাস চালু থাকলে অন্য যেকোনো কপির মতোই সেখানে সংরক্ষিত হয়।",
                ur: "ترجمہ ایک عام اندراج کے طور پر کلپ بورڈ میں چلا جاتا ہے — اور اگر ہسٹری فعال ہو تو کسی بھی دوسری کاپی کی طرح اُس میں محفوظ ہو جاتا ہے۔",
                zh: "翻译会作为普通内容写入剪贴板；如果启用了历史记录，它也会像其他复制操作一样被保存下来。");

            Add("Сразу вставлять перевод вместо выделения",
                en: "Paste the translation over the selection right away",
                uk: "Одразу вставляти переклад замість виділення",
                de: "Übersetzung sofort anstelle der Auswahl einfügen",
                it: "Incolla subito la traduzione al posto della selezione",
                es: "Pegar la traducción sobre la selección de inmediato",
                fr: "Coller aussitôt la traduction à la place de la sélection",
                pt: "Substituir de imediato a seleção pela tradução",
                ar: "لصق الترجمة فورًا بدلًا من النص المحدد",
                hi: "अनुवाद को तुरंत चयनित टेक्स्ट की जगह चिपकाएँ",
                bn: "নির্বাচিত লেখার বদলে অনুবাদ সঙ্গে সঙ্গে বসান",
                ur: "ترجمہ فوراً منتخب متن کی جگہ چسپاں کریں",
                zh: "立即用翻译替换选中的文本");

            Add("Сразу заменяет выделение переводом. Если к моменту ответа фокус ушёл в другое окно, вставки не будет — окно предложит вставить вручную.",
                en: "Replaces the selection with the translation. If the focus has moved to another window by the time the answer arrives nothing is pasted, and the window offers to paste it by hand.",
                uk: "Одразу замінює виділення перекладом. Якщо на момент відповіді фокус перейшов в інше вікно, вставки не буде — вікно запропонує вставити вручну.",
                de: "Ersetzt die Auswahl unmittelbar durch die Übersetzung. Liegt der Fokus zum Zeitpunkt der Antwort in einem anderen Fenster, wird nichts eingefügt — das Fenster bietet dann das manuelle Einfügen an.",
                it: "Sostituisce subito la selezione con la traduzione. Se al momento della risposta il focus è passato a un'altra finestra, non viene incollato nulla: la finestra proporrà di incollare manualmente.",
                es: "Sustituye la selección por la traducción al instante. Si al llegar la respuesta el foco ya está en otra ventana, no se pegará nada: la ventana ofrecerá pegarla manualmente.",
                fr: "Remplace immédiatement la sélection par la traduction. Si le focus est passé à une autre fenêtre au moment de la réponse, rien n'est collé : la fenêtre propose alors de coller manuellement.",
                pt: "Substitui a seleção pela tradução. Se, quando a resposta chegar, o foco já tiver passado para outra janela, nada é colado e a janela propõe colar manualmente.",
                ar: "يستبدل النص المحدد بالترجمة فورًا. وإذا انتقل التركيز إلى نافذة أخرى قبل وصول الرد، فلن يحدث اللصق، وستعرض نافذة النتيجة لصقها يدويًا.",
                hi: "चयनित टेक्स्ट को तुरंत अनुवाद से बदल देता है। अगर जवाब आने तक फ़ोकस किसी दूसरी विंडो में चला गया, तो कुछ नहीं चिपकाया जाएगा — विंडो उसे हाथ से चिपकाने का विकल्प देगी।",
                bn: "নির্বাচিত লেখাটি সঙ্গে সঙ্গে অনুবাদ দিয়ে বদলে দেয়। উত্তর আসার আগেই ফোকাস অন্য উইন্ডোতে চলে গেলে কিছু বসানো হবে না — উইন্ডোটি হাতে পেস্ট করার প্রস্তাব দেবে।",
                ur: "منتخب متن کو فوراً ترجمے سے بدل دیتا ہے۔ اگر جواب آنے تک فوکس کسی دوسری ونڈو میں چلا گیا ہو تو کچھ چسپاں نہیں ہوگا — ونڈو خود سے چسپاں کرنے کی پیشکش کرے گی۔",
                zh: "直接用翻译替换选中的文本。如果收到结果时焦点已切换到其他窗口，则不会粘贴，窗口会提示您手动粘贴。");

            Add("Показывать исходный текст рядом с переводом",
                en: "Show the source text next to the translation",
                uk: "Показувати вихідний текст поряд із перекладом",
                de: "Ausgangstext neben der Übersetzung anzeigen",
                it: "Mostra il testo originale accanto alla traduzione",
                es: "Mostrar el texto original junto a la traducción",
                fr: "Afficher le texte source à côté de la traduction",
                pt: "Mostrar o texto original junto da tradução",
                ar: "عرض النص الأصلي بجانب الترجمة",
                hi: "अनुवाद के साथ मूल टेक्स्ट भी दिखाएँ",
                bn: "অনুবাদের পাশে মূল লেখা দেখান",
                ur: "اصل متن ترجمے کے ساتھ دکھائیں",
                zh: "在翻译旁显示原文");

            Add("Показывает исходный текст в верхней части окна результата.",
                en: "Shows the source text at the top of the result window.",
                uk: "Показує вихідний текст у верхній частині вікна результату.",
                de: "Zeigt den Ausgangstext im oberen Teil des Ergebnisfensters.",
                it: "Mostra il testo originale nella parte superiore della finestra del risultato.",
                es: "Muestra el texto original en la parte superior de la ventana de resultado.",
                fr: "Affiche le texte source dans la partie supérieure de la fenêtre de résultat.",
                pt: "Mostra o texto original na parte superior da janela de resultado.",
                ar: "يعرض النص الأصلي في أعلى نافذة النتيجة.",
                hi: "मूल टेक्स्ट को परिणाम विंडो के ऊपरी हिस्से में दिखाता है।",
                bn: "ফলাফল উইন্ডোর উপরের অংশে মূল লেখা দেখায়।",
                ur: "اصل متن نتیجے کی ونڈو کے اوپری حصے میں دکھاتا ہے۔",
                zh: "在结果窗口顶部显示原文。");

            Add("Закрывать окно через (с):",
                en: "Close the window after (s):",
                uk: "Закривати вікно через (с):",
                de: "Fenster schließen nach (Sek.):",
                it: "Chiudi la finestra dopo (s):",
                es: "Cerrar la ventana después de (s):",
                fr: "Fermer la fenêtre au bout de (s) :",
                pt: "Fechar a janela ao fim de (s):",
                ar: "إغلاق النافذة بعد (ث):",
                hi: "विंडो इतनी देर बाद बंद करें (सेकंड):",
                bn: "উইন্ডো বন্ধ করার সময় (সেকেন্ড):",
                ur: "ونڈو بند کرنے کا وقفہ (سیکنڈ):",
                zh: "自动关闭窗口（秒）：");

            Add("0 — не закрывать по таймеру. Окно и так закроется по Esc, по кнопке закрытия или когда вы перейдёте в другое окно.",
                en: "0 means no timer. The window still closes on Esc, on its close button, or when you move to another window.",
                uk: "0 — не закривати за таймером. Вікно й так закриється за Esc, кнопкою закриття або коли ви перейдете в інше вікно.",
                de: "0 bedeutet kein Timer. Das Fenster schließt sich ohnehin mit Esc, über die Schließen-Schaltfläche oder sobald Sie in ein anderes Fenster wechseln.",
                it: "0 disattiva la chiusura a tempo. La finestra si chiude comunque con Esc, con il pulsante di chiusura o quando passi a un'altra finestra.",
                es: "0: no cerrar por temporizador. La ventana se cierra igualmente con Esc, con su botón de cierre o cuando pase a otra ventana.",
                fr: "0 désactive la minuterie. La fenêtre se ferme de toute façon avec Esc, avec son bouton de fermeture ou lorsque vous passez à une autre fenêtre.",
                pt: "Com 0 não há temporizador. A janela fecha-se na mesma com Esc, com o botão de fecho ou quando mudar para outra janela.",
                ar: "القيمة 0 تعني عدم الإغلاق بمؤقّت. وتُغلَق النافذة على أي حال بمفتاح Esc أو بزر الإغلاق أو عند الانتقال إلى نافذة أخرى.",
                hi: "0 का मतलब है टाइमर से बंद न करना। विंडो वैसे भी Esc से, बंद करने वाले बटन से या किसी दूसरी विंडो में जाने पर बंद हो जाती है।",
                bn: "0 দিলে টাইমারে বন্ধ হবে না। Esc চাপলে, বন্ধ করার বোতামে ক্লিক করলে বা অন্য উইন্ডোতে গেলে উইন্ডোটি এমনিতেই বন্ধ হয়ে যায়।",
                ur: "0 کا مطلب کوئی ٹائمر نہیں۔ ونڈو یوں بھی Esc دبانے سے، بند کرنے کے بٹن سے یا آپ کے کسی دوسری ونڈو میں جانے پر بند ہو جاتی ہے۔",
                zh: "0 表示不定时关闭。窗口仍可以按 Esc、点击关闭按钮或切换到其他窗口来关闭。");

            // ---- The direction table ----
            Add("На язык",
                en: "Into language",
                uk: "На мову",
                de: "Zielsprache",
                it: "Lingua di destinazione",
                es: "Idioma de destino",
                fr: "Vers la langue",
                pt: "Para o idioma",
                ar: "إلى اللغة",
                hi: "लक्ष्य भाषा",
                bn: "যে ভাষায়",
                ur: "کس زبان میں",
                zh: "目标语言");

            Add("Направлений пока нет — добавьте первое, чтобы назначить комбинацию.",
                en: "No directions yet - add the first one to assign a chord.",
                uk: "Напрямків поки немає — додайте перший, щоб призначити комбінацію.",
                de: "Noch keine Richtungen — fügen Sie die erste hinzu, um eine Kombination zuzuweisen.",
                it: "Non c'è ancora nessuna direzione: aggiungi la prima per assegnare una combinazione.",
                es: "Todavía no hay direcciones: añada la primera para asignar una combinación.",
                fr: "Aucun sens de traduction pour l'instant : ajoutez le premier pour attribuer une combinaison.",
                pt: "Ainda não há direções — adicione a primeira para atribuir uma combinação.",
                ar: "لا توجد اتجاهات بعد — أضف الأول لتعيين اختصار المفاتيح.",
                hi: "अभी कोई दिशा नहीं है — कुंजी संयोजन असाइन करने के लिए पहली दिशा जोड़ें।",
                bn: "এখনো কোনো দিক নেই — শর্টকাট নির্ধারণ করতে প্রথমটি যোগ করুন।",
                ur: "ابھی کوئی سمت نہیں ہے — کلیدی مجموعہ مقرر کرنے کے لیے پہلی سمت شامل کریں۔",
                zh: "尚未添加任何方向，请先添加第一个以分配组合键。");

            // ---- The Ollama status line (one label for the whole tab) ----
            Add("Ollama уже установлен — нажмите «Запустить Ollama».",
                en: "Ollama is already installed - press \"Start Ollama\".",
                uk: "Ollama вже встановлено — натисніть «Запустити Ollama».",
                de: "Ollama ist bereits installiert — klicken Sie auf «Ollama starten».",
                it: "Ollama è già installato: fai clic su «Avvia Ollama».",
                es: "Ollama ya está instalado: pulse «Iniciar Ollama».",
                fr: "Ollama est déjà installé : cliquez sur « Démarrer Ollama ».",
                pt: "O Ollama já está instalado — clique em «Iniciar o Ollama».",
                ar: "Ollama مثبَّت بالفعل — اضغط «تشغيل Ollama».",
                hi: "Ollama पहले से इंस्टॉल है — “Ollama शुरू करें” दबाएँ।",
                bn: "Ollama ইতিমধ্যেই ইনস্টল করা আছে — “Ollama চালু করুন” চাপুন।",
                ur: "Ollama پہلے سے انسٹال ہے — ”Ollama چلائیں“ دبائیں۔",
                zh: "Ollama 已安装，请点击「启动 Ollama」。");

            Add("Открываю сайт Ollama — установите его оттуда.",
                en: "Opening the Ollama website - install it from there.",
                uk: "Відкриваю сайт Ollama — встановіть його звідти.",
                de: "Die Ollama-Website wird geöffnet — installieren Sie Ollama von dort.",
                it: "Apertura del sito di Ollama: installalo da lì.",
                es: "Abriendo el sitio web de Ollama: instálelo desde ahí.",
                fr: "Ouverture du site d'Ollama : installez-le depuis ce site.",
                pt: "A abrir o site do Ollama — instale-o a partir daí.",
                ar: "جارٍ فتح موقع Ollama — ثبّته من هناك.",
                hi: "Ollama की वेबसाइट खोली जा रही है — उसे वहीं से इंस्टॉल करें।",
                bn: "Ollama-র সাইট খোলা হচ্ছে — সেখান থেকে ইনস্টল করুন।",
                ur: "Ollama کی ویب سائٹ کھولی جا رہی ہے — اسے وہیں سے انسٹال کریں۔",
                zh: "正在打开 Ollama 官网，请从那里安装。");

            Add("Скачать и установить Ollama? Это несколько сотен мегабайт, загрузка может занять время.",
                en: "Download and install Ollama? This is several hundred megabytes and may take a while.",
                uk: "Завантажити та встановити Ollama? Це кілька сотень мегабайтів, завантаження може тривати деякий час.",
                de: "Ollama herunterladen und installieren? Das sind mehrere Hundert Megabyte, der Download kann eine Weile dauern.",
                it: "Scaricare e installare Ollama? Sono diverse centinaia di megabyte, il download può richiedere tempo.",
                es: "¿Descargar e instalar Ollama? Son varios cientos de megabytes y la descarga puede tardar.",
                fr: "Télécharger et installer Ollama ? Le fichier pèse plusieurs centaines de mégaoctets, le téléchargement peut prendre du temps.",
                pt: "Transferir e instalar o Ollama? São várias centenas de megabytes e a transferência pode demorar.",
                ar: "هل تريد تنزيل Ollama وتثبيته؟ حجمه عدة مئات من الميغابايتات، وقد يستغرق التنزيل بعض الوقت.",
                hi: "Ollama डाउनलोड करके इंस्टॉल करें? यह कई सौ मेगाबाइट का है, डाउनलोड में समय लग सकता है।",
                bn: "Ollama ডাউনলোড করে ইনস্টল করবেন? এটি কয়েকশো মেগাবাইটের, ডাউনলোডে কিছুটা সময় লাগতে পারে।",
                ur: "Ollama ڈاؤن لوڈ کر کے انسٹال کریں؟ یہ کئی سو میگا بائٹ ہے اور ڈاؤن لوڈ میں وقت لگ سکتا ہے۔",
                zh: "要下载并安装 Ollama 吗？文件有几百 MB，下载可能需要一些时间。");

            Add("Скачиваю Ollama...",
                en: "Downloading Ollama...",
                uk: "Завантажую Ollama...",
                de: "Ollama wird heruntergeladen...",
                it: "Download di Ollama in corso...",
                es: "Descargando Ollama...",
                fr: "Téléchargement d'Ollama...",
                pt: "A transferir o Ollama...",
                ar: "جارٍ تنزيل Ollama...",
                hi: "Ollama डाउनलोड हो रहा है...",
                bn: "Ollama ডাউনলোড করা হচ্ছে...",
                ur: "Ollama ڈاؤن لوڈ ہو رہا ہے...",
                zh: "正在下载 Ollama...");

            Add("Скачиваю Ollama:",
                en: "Downloading Ollama:",
                uk: "Завантажую Ollama:",
                de: "Ollama wird heruntergeladen:",
                it: "Download di Ollama:",
                es: "Descargando Ollama:",
                fr: "Téléchargement d'Ollama :",
                pt: "A transferir o Ollama:",
                ar: "جارٍ تنزيل Ollama:",
                hi: "Ollama डाउनलोड हो रहा है:",
                bn: "Ollama ডাউনলোড করা হচ্ছে:",
                ur: "Ollama ڈاؤن لوڈ ہو رہا ہے:",
                zh: "正在下载 Ollama：");

            Add("Запускаю установщик Ollama...",
                en: "Launching the Ollama installer...",
                uk: "Запускаю інсталятор Ollama...",
                de: "Das Ollama-Installationsprogramm wird gestartet...",
                it: "Avvio del programma di installazione di Ollama...",
                es: "Iniciando el instalador de Ollama...",
                fr: "Lancement du programme d'installation d'Ollama...",
                pt: "A iniciar o instalador do Ollama...",
                ar: "جارٍ تشغيل مثبِّت Ollama...",
                hi: "Ollama का इंस्टॉलर चलाया जा रहा है...",
                bn: "Ollama-র ইনস্টলার চালু করা হচ্ছে...",
                ur: "Ollama کا انسٹالر چلایا جا رہا ہے...",
                zh: "正在启动 Ollama 安装程序...");

            Add("Не удалось скачать. Открываю сайт Ollama...",
                en: "The download failed. Opening the Ollama website...",
                uk: "Не вдалося завантажити. Відкриваю сайт Ollama...",
                de: "Der Download ist fehlgeschlagen. Die Ollama-Website wird geöffnet...",
                it: "Download non riuscito. Apertura del sito di Ollama...",
                es: "No se pudo descargar. Abriendo el sitio web de Ollama...",
                fr: "Échec du téléchargement. Ouverture du site d'Ollama...",
                pt: "Não foi possível transferir. A abrir o site do Ollama...",
                ar: "تعذّر التنزيل. جارٍ فتح موقع Ollama...",
                hi: "डाउनलोड नहीं हो सका। Ollama की वेबसाइट खोली जा रही है...",
                bn: "ডাউনলোড করা যায়নি। Ollama-র সাইট খোলা হচ্ছে...",
                ur: "ڈاؤن لوڈ نہیں ہو سکا۔ Ollama کی ویب سائٹ کھولی جا رہی ہے...",
                zh: "下载失败。正在打开 Ollama 官网...");

            Add("Ollama не установлен — нажмите «Установить Ollama».",
                en: "Ollama is not installed - press \"Install Ollama\".",
                uk: "Ollama не встановлено — натисніть «Встановити Ollama».",
                de: "Ollama ist nicht installiert — klicken Sie auf «Ollama installieren».",
                it: "Ollama non è installato: fai clic su «Installa Ollama».",
                es: "Ollama no está instalado: pulse «Instalar Ollama».",
                fr: "Ollama n'est pas installé : cliquez sur « Installer Ollama ».",
                pt: "O Ollama não está instalado — clique em «Instalar o Ollama».",
                ar: "Ollama غير مثبَّت — اضغط «تثبيت Ollama».",
                hi: "Ollama इंस्टॉल नहीं है — “Ollama इंस्टॉल करें” दबाएँ।",
                bn: "Ollama ইনস্টল করা নেই — “Ollama ইনস্টল করুন” চাপুন।",
                ur: "Ollama انسٹال نہیں ہے — ”Ollama انسٹال کریں“ دبائیں۔",
                zh: "尚未安装 Ollama，请点击「安装 Ollama」。");

            Add("Запускаю Ollama...",
                en: "Starting Ollama...",
                uk: "Запускаю Ollama...",
                de: "Ollama wird gestartet...",
                it: "Avvio di Ollama in corso...",
                es: "Iniciando Ollama...",
                fr: "Démarrage d'Ollama...",
                pt: "A iniciar o Ollama...",
                ar: "جارٍ تشغيل Ollama...",
                hi: "Ollama शुरू किया जा रहा है...",
                bn: "Ollama চালু করা হচ্ছে...",
                ur: "Ollama چلایا جا رہا ہے...",
                zh: "正在启动 Ollama...");

            Add("Не удалось запустить Ollama.",
                en: "Could not start Ollama.",
                uk: "Не вдалося запустити Ollama.",
                de: "Ollama konnte nicht gestartet werden.",
                it: "Non è stato possibile avviare Ollama.",
                es: "No se pudo iniciar Ollama.",
                fr: "Impossible de démarrer Ollama.",
                pt: "Não foi possível iniciar o Ollama.",
                ar: "تعذّر تشغيل Ollama.",
                hi: "Ollama शुरू नहीं हो सका।",
                bn: "Ollama চালু করা যায়নি।",
                ur: "Ollama چلایا نہیں جا سکا۔",
                zh: "无法启动 Ollama。");

            Add("Ollama не запущен — нажмите «Запустить Ollama».",
                en: "Ollama is not running - press \"Start Ollama\".",
                uk: "Ollama не запущено — натисніть «Запустити Ollama».",
                de: "Ollama läuft nicht — klicken Sie auf «Ollama starten».",
                it: "Ollama non è in esecuzione: fai clic su «Avvia Ollama».",
                es: "Ollama no está en ejecución: pulse «Iniciar Ollama».",
                fr: "Ollama n'est pas démarré : cliquez sur « Démarrer Ollama ».",
                pt: "O Ollama não está em execução — clique em «Iniciar o Ollama».",
                ar: "Ollama لا يعمل — اضغط «تشغيل Ollama».",
                hi: "Ollama चल नहीं रहा — “Ollama शुरू करें” दबाएँ।",
                bn: "Ollama চালু নেই — “Ollama চালু করুন” চাপুন।",
                ur: "Ollama چل نہیں رہا — ”Ollama چلائیں“ دبائیں۔",
                zh: "Ollama 未在运行，请点击「启动 Ollama」。");

            Add("Ollama не найден — нажмите «Установить Ollama».",
                en: "Ollama was not found - press \"Install Ollama\".",
                uk: "Ollama не знайдено — натисніть «Встановити Ollama».",
                de: "Ollama wurde nicht gefunden — klicken Sie auf «Ollama installieren».",
                it: "Ollama non è stato trovato: fai clic su «Installa Ollama».",
                es: "No se encontró Ollama: pulse «Instalar Ollama».",
                fr: "Ollama est introuvable : cliquez sur « Installer Ollama ».",
                pt: "O Ollama não foi encontrado — clique em «Instalar o Ollama».",
                ar: "تعذّر العثور على Ollama — اضغط «تثبيت Ollama».",
                hi: "Ollama नहीं मिला — “Ollama इंस्टॉल करें” दबाएँ।",
                bn: "Ollama পাওয়া যায়নি — “Ollama ইনস্টল করুন” চাপুন।",
                ur: "Ollama نہیں ملا — ”Ollama انسٹال کریں“ دبائیں۔",
                zh: "未找到 Ollama，请点击「安装 Ollama」。");

            Add("Укажите имя модели, например qwen2.5:3b.",
                en: "Enter a model name, for example qwen2.5:3b.",
                uk: "Укажіть назву моделі, наприклад qwen2.5:3b.",
                de: "Geben Sie einen Modellnamen an, zum Beispiel qwen2.5:3b.",
                it: "Indica il nome di un modello, ad esempio qwen2.5:3b.",
                es: "Indique el nombre del modelo, por ejemplo qwen2.5:3b.",
                fr: "Indiquez un nom de modèle, par exemple qwen2.5:3b.",
                pt: "Indique o nome de um modelo, por exemplo qwen2.5:3b.",
                ar: "أدخل اسم النموذج، مثل qwen2.5:3b.",
                hi: "मॉडल का नाम बताएँ, जैसे qwen2.5:3b।",
                bn: "মডেলের নাম লিখুন, যেমন qwen2.5:3b।",
                ur: "ماڈل کا نام درج کریں، مثلاً qwen2.5:3b۔",
                zh: "请填写模型名称，例如 qwen2.5:3b。");

            Add("Загружаю модель:",
                en: "Downloading the model:",
                uk: "Завантажую модель:",
                de: "Modell wird heruntergeladen:",
                it: "Download del modello:",
                es: "Descargando el modelo:",
                fr: "Téléchargement du modèle :",
                pt: "A transferir o modelo:",
                ar: "جارٍ تنزيل النموذج:",
                hi: "मॉडल डाउनलोड हो रहा है:",
                bn: "মডেল ডাউনলোড করা হচ্ছে:",
                ur: "ماڈل ڈاؤن لوڈ ہو رہا ہے:",
                zh: "正在下载模型：");

            Add("Модель установлена:",
                en: "Model installed:",
                uk: "Модель встановлено:",
                de: "Modell installiert:",
                it: "Modello installato:",
                es: "Modelo instalado:",
                fr: "Modèle installé :",
                pt: "Modelo instalado:",
                ar: "تم تثبيت النموذج:",
                hi: "मॉडल इंस्टॉल हो गया:",
                bn: "মডেল ইনস্টল হয়েছে:",
                ur: "ماڈل انسٹال ہو گیا:",
                zh: "模型已安装：");

            Add("Не удалось загрузить модель. Ollama запущен?",
                en: "Could not download the model. Is Ollama running?",
                uk: "Не вдалося завантажити модель. Ollama запущено?",
                de: "Das Modell konnte nicht heruntergeladen werden. Läuft Ollama?",
                it: "Non è stato possibile scaricare il modello. Ollama è in esecuzione?",
                es: "No se pudo descargar el modelo. ¿Está Ollama en ejecución?",
                fr: "Impossible de télécharger le modèle. Ollama est-il démarré ?",
                pt: "Não foi possível transferir o modelo. O Ollama está em execução?",
                ar: "تعذّر تنزيل النموذج. هل Ollama يعمل؟",
                hi: "मॉडल डाउनलोड नहीं हो सका। क्या Ollama चल रहा है?",
                bn: "মডেল ডাউনলোড করা যায়নি। Ollama কি চালু আছে?",
                ur: "ماڈل ڈاؤن لوڈ نہیں ہو سکا۔ کیا Ollama چل رہا ہے؟",
                zh: "无法下载模型。Ollama 正在运行吗？");

            Add("Ollama работает. Установленные модели:",
                en: "Ollama is running. Installed models:",
                uk: "Ollama працює. Встановлені моделі:",
                de: "Ollama läuft. Installierte Modelle:",
                it: "Ollama è in esecuzione. Modelli installati:",
                es: "Ollama está en ejecución. Modelos instalados:",
                fr: "Ollama fonctionne. Modèles installés :",
                pt: "O Ollama está em execução. Modelos instalados:",
                ar: "Ollama يعمل. النماذج المثبَّتة:",
                hi: "Ollama चल रहा है। इंस्टॉल किए गए मॉडल:",
                bn: "Ollama চলছে। ইনস্টল করা মডেল:",
                ur: "Ollama چل رہا ہے۔ انسٹال شدہ ماڈل:",
                zh: "Ollama 正在运行。已安装的模型：");

            Add("Ollama работает, но ни одна модель не установлена — нажмите «Загрузить модель».",
                en: "Ollama is running but no model is installed - press \"Download the model\".",
                uk: "Ollama працює, але жодної моделі не встановлено — натисніть «Завантажити модель».",
                de: "Ollama läuft, aber es ist kein Modell installiert — klicken Sie auf «Modell herunterladen».",
                it: "Ollama è in esecuzione, ma non è installato alcun modello: fai clic su «Scarica il modello».",
                es: "Ollama está en ejecución, pero no hay ningún modelo instalado: pulse «Descargar modelo».",
                fr: "Ollama fonctionne, mais aucun modèle n'est installé : cliquez sur « Télécharger le modèle ».",
                pt: "O Ollama está em execução, mas não há nenhum modelo instalado — clique em «Transferir modelo».",
                ar: "Ollama يعمل، لكن لا يوجد أي نموذج مثبَّت — اضغط «تنزيل النموذج».",
                hi: "Ollama चल रहा है, पर कोई भी मॉडल इंस्टॉल नहीं है — “मॉडल डाउनलोड करें” दबाएँ।",
                bn: "Ollama চলছে, কিন্তু কোনো মডেল ইনস্টল করা নেই — “মডেল ডাউনলোড করুন” চাপুন।",
                ur: "Ollama چل رہا ہے، مگر کوئی ماڈل انسٹال نہیں — ”ماڈل ڈاؤن لوڈ کریں“ دبائیں۔",
                zh: "Ollama 正在运行，但尚未安装任何模型，请点击「下载模型」。");

            // ---- The row editor ----
            Add("Новое направление перевода",
                en: "New translation direction",
                uk: "Новий напрямок перекладу",
                de: "Neue Übersetzungsrichtung",
                it: "Nuova direzione di traduzione",
                es: "Nueva dirección de traducción",
                fr: "Nouveau sens de traduction",
                pt: "Nova direção de tradução",
                ar: "اتجاه ترجمة جديد",
                hi: "नई अनुवाद दिशा",
                bn: "অনুবাদের নতুন দিক",
                ur: "ترجمے کی نئی سمت",
                zh: "新建翻译方向");

            Add("Изменить направление перевода",
                en: "Edit the translation direction",
                uk: "Змінити напрямок перекладу",
                de: "Übersetzungsrichtung bearbeiten",
                it: "Modifica la direzione di traduzione",
                es: "Editar la dirección de traducción",
                fr: "Modifier le sens de traduction",
                pt: "Editar a direção de tradução",
                ar: "تعديل اتجاه الترجمة",
                hi: "अनुवाद दिशा बदलें",
                bn: "অনুবাদের দিক সম্পাদনা করুন",
                ur: "ترجمے کی سمت میں ترمیم",
                zh: "编辑翻译方向");

            Add("Переводить на:",
                en: "Translate into:",
                uk: "Перекладати на:",
                de: "Übersetzen in:",
                it: "Traduci in:",
                es: "Traducir a:",
                fr: "Traduire vers :",
                pt: "Traduzir para:",
                ar: "الترجمة إلى:",
                hi: "इस भाषा में अनुवाद करें:",
                bn: "যে ভাষায় অনুবাদ করা হবে:",
                ur: "اس زبان میں ترجمہ کریں:",
                zh: "翻译成：");

            Add("Комбинация для перевода",
                en: "Translation chord",
                uk: "Комбінація для перекладу",
                de: "Kombination für die Übersetzung",
                it: "Combinazione per la traduzione",
                es: "Combinación para traducir",
                fr: "Combinaison pour la traduction",
                pt: "Combinação de teclas para traduzir",
                ar: "اختصار المفاتيح للترجمة",
                hi: "अनुवाद का कुंजी संयोजन",
                bn: "অনুবাদের শর্টকাট",
                ur: "ترجمے کا کلیدی مجموعہ",
                zh: "翻译组合键");

            // ---- The result window near the cursor ----
            Add("Копировать",
                en: "Copy",
                uk: "Копіювати",
                de: "Kopieren",
                it: "Copia",
                es: "Copiar",
                fr: "Copier",
                pt: "Copiar",
                ar: "نسخ",
                hi: "कॉपी करें",
                bn: "কপি করুন",
                ur: "کاپی کریں",
                zh: "复制");

            Add("Вставить",
                en: "Paste",
                uk: "Вставити",
                de: "Einfügen",
                it: "Incolla",
                es: "Pegar",
                fr: "Coller",
                pt: "Colar",
                ar: "لصق",
                hi: "चिपकाएँ",
                bn: "পেস্ট করুন",
                ur: "چسپاں کریں",
                zh: "粘贴");

            Add("Ещё раз",
                en: "Again",
                uk: "Ще раз",
                de: "Wiederholen",
                it: "Ripeti",
                es: "Repetir",
                fr: "Réessayer",
                pt: "Repetir",
                ar: "مرة أخرى",
                hi: "फिर से",
                bn: "আবার",
                ur: "دوبارہ",
                zh: "重新翻译");

            Add("Настройки",
                en: "Settings",
                uk: "Налаштування",
                de: "Einstellungen",
                it: "Impostazioni",
                es: "Configuración",
                fr: "Paramètres",
                pt: "Definições",
                ar: "الإعدادات",
                hi: "सेटिंग्स",
                bn: "সেটিংস",
                ur: "ترتیبات",
                zh: "设置");

            Add("Язык интерфейса",
                en: "Interface language",
                uk: "Мова інтерфейсу",
                de: "Oberflächensprache",
                it: "Lingua dell'interfaccia",
                es: "Idioma de la interfaz",
                fr: "Langue de l'interface",
                pt: "Idioma da interface",
                ar: "لغة الواجهة",
                hi: "इंटरफ़ेस की भाषा",
                bn: "ইন্টারফেসের ভাষা",
                ur: "انٹرفیس کی زبان",
                zh: "界面语言");

            Add("Язык активной раскладки",
                en: "Active layout language",
                uk: "Мова активної розкладки",
                de: "Sprache des aktiven Layouts",
                it: "Lingua del layout attivo",
                es: "Idioma de la distribución activa",
                fr: "Langue de la disposition active",
                pt: "Idioma do esquema de teclado ativo",
                ar: "لغة تخطيط لوحة المفاتيح النشط",
                hi: "सक्रिय लेआउट की भाषा",
                bn: "সক্রিয় লেআউটের ভাষা",
                ur: "فعال لے آؤٹ کی زبان",
                zh: "当前键盘布局语言");

            // ---- Tray entry, progress and the messages the result window shows ----
            Add("Перевести буфер обмена",
                en: "Translate the clipboard",
                uk: "Перекласти буфер обміну",
                de: "Zwischenablage übersetzen",
                it: "Traduci gli appunti",
                es: "Traducir el portapapeles",
                fr: "Traduire le presse-papiers",
                pt: "Traduzir a área de transferência",
                ar: "ترجمة الحافظة",
                hi: "क्लिपबोर्ड का अनुवाद करें",
                bn: "ক্লিপবোর্ড অনুবাদ করুন",
                ur: "کلپ بورڈ کا ترجمہ کریں",
                zh: "翻译剪贴板内容");

            Add("В буфере обмена нет текста для перевода.",
                en: "There is no text on the clipboard to translate.",
                uk: "У буфері обміну немає тексту для перекладу.",
                de: "In der Zwischenablage befindet sich kein Text zum Übersetzen.",
                it: "Negli appunti non c'è testo da tradurre.",
                es: "No hay texto en el portapapeles para traducir.",
                fr: "Le presse-papiers ne contient aucun texte à traduire.",
                pt: "Não há texto na área de transferência para traduzir.",
                ar: "لا يوجد نص في الحافظة للترجمة.",
                hi: "क्लिपबोर्ड में अनुवाद के लिए कोई टेक्स्ट नहीं है।",
                bn: "ক্লিপবোর্ডে অনুবাদ করার মতো কোনো লেখা নেই।",
                ur: "کلپ بورڈ میں ترجمے کے لیے کوئی متن نہیں ہے۔",
                zh: "剪贴板中没有可翻译的文本。");

            Add("Перевожу… (Esc — отмена)",
                en: "Translating... (Esc to cancel)",
                uk: "Перекладаю… (Esc — скасувати)",
                de: "Übersetzung läuft… (Esc zum Abbrechen)",
                it: "Traduzione in corso… (Esc per annullare)",
                es: "Traduciendo… (Esc para cancelar)",
                fr: "Traduction en cours… (Esc pour annuler)",
                pt: "A traduzir… (Esc para cancelar)",
                ar: "جارٍ الترجمة… (Esc للإلغاء)",
                hi: "अनुवाद हो रहा है… (Esc — रद्द करें)",
                bn: "অনুবাদ করা হচ্ছে… (বাতিল করতে Esc)",
                ur: "ترجمہ ہو رہا ہے... (Esc سے منسوخ کریں)",
                zh: "正在翻译…（按 Esc 取消）");

            Add("переведены первые {0} из {1} символов",
                en: "the first {0} of {1} characters were translated",
                uk: "перекладено перші {0} з {1} символів",
                de: "die ersten {0} von {1} Zeichen wurden übersetzt",
                it: "tradotti i primi {0} caratteri su {1}",
                es: "se han traducido los primeros {0} de {1} caracteres",
                fr: "les {0} premiers caractères sur {1} ont été traduits",
                pt: "foram traduzidos os primeiros {0} de {1} carateres",
                ar: "تُرجم أول {0} حرف من أصل {1}",
                hi: "{1} में से पहले {0} अक्षरों का अनुवाद किया गया",
                bn: "{1}টি অক্ষরের মধ্যে প্রথম {0}টি অনুবাদ করা হয়েছে",
                ur: "{1} میں سے پہلے {0} حروف کا ترجمہ ہوا",
                zh: "已翻译前 {0} 个字符（共 {1} 个）");

            Add("Фокус сменился — вставьте перевод вручную.",
                en: "The focus has moved - paste the translation by hand.",
                uk: "Фокус змінився — вставте переклад вручну.",
                de: "Der Fokus hat gewechselt — fügen Sie die Übersetzung manuell ein.",
                it: "Il focus è cambiato: incolla la traduzione manualmente.",
                es: "El foco ha cambiado: pegue la traducción manualmente.",
                fr: "Le focus a changé : collez la traduction manuellement.",
                pt: "O foco mudou — cole a tradução manualmente.",
                ar: "تغيّر التركيز — الصق الترجمة يدويًا.",
                hi: "फ़ोकस बदल गया — अनुवाद हाथ से चिपकाएँ।",
                bn: "ফোকাস বদলে গেছে — অনুবাদটি হাতে পেস্ট করুন।",
                ur: "فوکس بدل گیا — ترجمہ خود سے چسپاں کریں۔",
                zh: "焦点已切换，请手动粘贴翻译。");

            Add("Нет текста для перевода.",
                en: "There is no text to translate.",
                uk: "Немає тексту для перекладу.",
                de: "Kein Text zum Übersetzen.",
                it: "Non c'è testo da tradurre.",
                es: "No hay texto para traducir.",
                fr: "Aucun texte à traduire.",
                pt: "Não há texto para traduzir.",
                ar: "لا يوجد نص للترجمة.",
                hi: "अनुवाद के लिए कोई टेक्स्ट नहीं है।",
                bn: "অনুবাদ করার মতো কোনো লেখা নেই।",
                ur: "ترجمے کے لیے کوئی متن نہیں ہے۔",
                zh: "没有可翻译的文本。");

            Add("Не найден Ollama — локальный переводчик. Его нужно установить один раз.",
                en: "Ollama, the local translator, was not found. It has to be installed once.",
                uk: "Не знайдено Ollama — локальний перекладач. Його потрібно встановити один раз.",
                de: "Ollama, der lokale Übersetzer, wurde nicht gefunden. Es muss einmalig installiert werden.",
                it: "Ollama, il traduttore locale, non è stato trovato. Va installato una volta sola.",
                es: "No se encontró Ollama, el traductor local. Hay que instalarlo una sola vez.",
                fr: "Ollama, le traducteur local, est introuvable. Il doit être installé une seule fois.",
                pt: "Não foi encontrado o Ollama, o tradutor local. É preciso instalá-lo uma vez.",
                ar: "تعذّر العثور على Ollama، المترجم المحلي. يجب تثبيته مرة واحدة.",
                hi: "स्थानीय अनुवादक Ollama नहीं मिला। उसे एक बार इंस्टॉल करना होगा।",
                bn: "স্থানীয় অনুবাদক Ollama পাওয়া যায়নি। এটি একবার ইনস্টল করে নিতে হবে।",
                ur: "مقامی مترجم Ollama نہیں ملا۔ اسے ایک بار انسٹال کرنا ہوگا۔",
                zh: "未找到本地翻译工具 Ollama。它需要先安装一次。");

            Add("Ollama не запущен.",
                en: "Ollama is not running.",
                uk: "Ollama не запущено.",
                de: "Ollama läuft nicht.",
                it: "Ollama non è in esecuzione.",
                es: "Ollama no está en ejecución.",
                fr: "Ollama n'est pas démarré.",
                pt: "O Ollama não está em execução.",
                ar: "Ollama لا يعمل.",
                hi: "Ollama चल नहीं रहा।",
                bn: "Ollama চালু নেই।",
                ur: "Ollama چل نہیں رہا۔",
                zh: "Ollama 未在运行。");

            Add("Не установлена ни одна модель. Рекомендуем qwen2.5:3b (~2 ГБ) — загрузите её в настройках.",
                en: "No model is installed. We recommend qwen2.5:3b (~2 GB) - download it in the settings.",
                uk: "Не встановлено жодної моделі. Рекомендуємо qwen2.5:3b (~2 ГБ) — завантажте її в налаштуваннях.",
                de: "Es ist kein Modell installiert. Wir empfehlen qwen2.5:3b (~2 GB) - laden Sie es in den Einstellungen herunter.",
                it: "Non è installato alcun modello. Consigliamo qwen2.5:3b (~2 GB): scaricalo nelle impostazioni.",
                es: "No hay ningún modelo instalado. Recomendamos qwen2.5:3b (~2 GB): descárguelo en la configuración.",
                fr: "Aucun modèle n'est installé. Nous recommandons qwen2.5:3b (~2 Go) - téléchargez-le dans les paramètres.",
                pt: "Não há nenhum modelo instalado. Recomendamos o qwen2.5:3b (~2 GB) - transfira-o nas definições.",
                ar: "لا يوجد أي نموذج مثبَّت. نوصي بـ qwen2.5:3b (‏~2 غيغابايت) — نزّله من الإعدادات.",
                hi: "कोई भी मॉडल इंस्टॉल नहीं है। हमारा सुझाव है qwen2.5:3b (~2 GB) — इसे सेटिंग्स में डाउनलोड करें।",
                bn: "কোনো মডেল ইনস্টল করা নেই। আমরা qwen2.5:3b (~2 GB) সুপারিশ করি — সেটিংস থেকে ডাউনলোড করুন।",
                ur: "کوئی ماڈل انسٹال نہیں ہے۔ ہم qwen2.5:3b (~2 GB) تجویز کرتے ہیں — اسے ترتیبات میں ڈاؤن لوڈ کریں۔",
                zh: "尚未安装任何模型。建议使用 qwen2.5:3b（约 2 GB），请在设置中下载。");

            Add("Ollama ответил ошибкой:",
                en: "Ollama answered with an error:",
                uk: "Ollama відповів помилкою:",
                de: "Ollama hat mit einem Fehler geantwortet:",
                it: "Ollama ha risposto con un errore:",
                es: "Ollama respondió con un error:",
                fr: "Ollama a répondu par une erreur :",
                pt: "O Ollama respondeu com um erro:",
                ar: "أجاب Ollama بخطأ:",
                hi: "Ollama ने त्रुटि के साथ उत्तर दिया:",
                bn: "Ollama একটি ত্রুটি জানিয়েছে:",
                ur: "Ollama نے خرابی کے ساتھ جواب دیا:",
                zh: "Ollama 返回了错误：");

            Add("Ollama не принял запрос. Проверьте адрес сервера и модель в настройках.",
                en: "Ollama refused the request. Check the server address and the model in the settings.",
                uk: "Ollama не прийняв запит. Перевірте адресу сервера й модель у налаштуваннях.",
                de: "Ollama hat die Anfrage abgelehnt. Prüfen Sie Serveradresse und Modell in den Einstellungen.",
                it: "Ollama ha rifiutato la richiesta. Controlla l'indirizzo del server e il modello nelle impostazioni.",
                es: "Ollama rechazó la solicitud. Compruebe la dirección del servidor y el modelo en la configuración.",
                fr: "Ollama a refusé la requête. Vérifiez l'adresse du serveur et le modèle dans les paramètres.",
                pt: "O Ollama recusou o pedido. Verifique o endereço do servidor e o modelo nas definições.",
                ar: "رفض Ollama الطلب. تحقّق من عنوان الخادم والنموذج في الإعدادات.",
                hi: "Ollama ने अनुरोध स्वीकार नहीं किया। सेटिंग्स में सर्वर पता और मॉडल जाँचें।",
                bn: "Ollama অনুরোধটি গ্রহণ করেনি। সেটিংসে সার্ভারের ঠিকানা ও মডেল যাচাই করুন।",
                ur: "Ollama نے درخواست قبول نہیں کی۔ ترتیبات میں سرور کا پتہ اور ماڈل جانچیں۔",
                zh: "Ollama 拒绝了该请求。请在设置中检查服务器地址和模型。");

            Add("Модель не ответила вовремя. Возможно, она слишком велика для этого компьютера.",
                en: "The model did not answer in time. It may be too large for this computer.",
                uk: "Модель не відповіла вчасно. Можливо, вона завелика для цього комп'ютера.",
                de: "Das Modell hat nicht rechtzeitig geantwortet. Möglicherweise ist es zu groß für diesen Computer.",
                it: "Il modello non ha risposto in tempo. Forse è troppo grande per questo computer.",
                es: "El modelo no respondió a tiempo. Puede que sea demasiado grande para este equipo.",
                fr: "Le modèle n'a pas répondu à temps. Il est peut-être trop lourd pour cet ordinateur.",
                pt: "O modelo não respondeu a tempo. Talvez seja demasiado grande para este computador.",
                ar: "لم يرد النموذج في الوقت المحدد. ربما يكون أكبر من قدرة هذا الجهاز.",
                hi: "मॉडल ने समय पर जवाब नहीं दिया। शायद यह इस कंप्यूटर के लिए बहुत बड़ा है।",
                bn: "মডেল সময়মতো উত্তর দেয়নি। সম্ভবত এটি এই কম্পিউটারের জন্য অনেক বড়।",
                ur: "ماڈل نے وقت پر جواب نہیں دیا۔ ممکن ہے یہ اس کمپیوٹر کے لیے بہت بڑا ہو۔",
                zh: "模型未能及时响应。它可能对这台电脑来说太大了。");

            Add("Модель не справилась с этим текстом.",
                en: "The model could not handle this text.",
                uk: "Модель не впоралася з цим текстом.",
                de: "Das Modell kam mit diesem Text nicht zurecht.",
                it: "Il modello non è riuscito a gestire questo testo.",
                es: "El modelo no pudo con este texto.",
                fr: "Le modèle n'a pas réussi à traiter ce texte.",
                pt: "O modelo não conseguiu lidar com este texto.",
                ar: "لم يتمكن النموذج من التعامل مع هذا النص.",
                hi: "मॉडल इस टेक्स्ट का अनुवाद नहीं कर सका।",
                bn: "মডেল এই লেখাটি সামলাতে পারেনি।",
                ur: "ماڈل اس متن کا ترجمہ نہیں کر سکا۔",
                zh: "模型无法处理这段文本。");

            Add("переводом текста",
                en: "text translation",
                uk: "перекладом тексту",
                de: "die Textübersetzung",
                it: "una traduzione del testo",
                es: "la traducción de texto",
                fr: "la traduction de texte",
                pt: "tradução de texto",
                ar: "ترجمة النص",
                hi: "टेक्स्ट अनुवाद",
                bn: "লেখার অনুবাদ",
                ur: "متن کا ترجمہ",
                zh: "文本翻译");
        }
    }
}
