"""Synchronize CyrFlip site metadata, search index and sitemap.

Run with --write after editing site pages; --check is a read-only release check.
Translation source hashes are deliberately refreshed only with --stamp-translations,
after the translated body has been reviewed against its English counterpart.
"""
import argparse
import hashlib
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
BASE = "https://serzhyale.github.io/CyrFlip/"
LOCALES = ("en", "ru", "uk", "de", "it", "es", "fr", "pt", "ar", "hi", "bn", "ur", "zh")
TRANSLATED = {"guide": ("en", "ru", "uk"), "privacy": LOCALES, "trust": LOCALES,
              "index": ("en", "de", "it", "es", "fr", "pt", "ar", "hi", "bn", "ur", "zh")}
SHORT_TITLES = {
    ("index", "es"): "CyrFlip - corregir texto con otra distribución",
    ("index", "fr"): "CyrFlip - corriger un texte saisi au mauvais clavier",
    ("index", "it"): "CyrFlip - correggere il testo nel layout sbagliato",
    ("index", "pt"): "CyrFlip - corrigir texto no layout errado",
    ("trust", "fr"): "CyrFlip - avertissement Windows ou antivirus",
    ("trust", "it"): "CyrFlip - avviso di Windows o antivirus",
    ("trust", "pt"): "CyrFlip - aviso do Windows ou antivírus",
}


def page(kind, locale):
    return DOCS / (kind + ".html" if locale == "en" else locale + "/" + ("index" if kind == "index" else kind) + ".html")


def url(kind, locale):
    return BASE + ("" if kind == "index" and locale == "en" else
                   locale + "/" if kind == "index" else
                   ("" if locale == "en" else locale + "/") + kind + ".html")


def source_hash(kind):
    source = page(kind, "en").read_text(encoding="utf-8")
    body = re.search(r"<body\b[^>]*>(.*)</body>", source, re.S | re.I).group(1)
    # Metadata, theme script and footer layout are outside the content fingerprint.
    body = re.split(r"<footer\b", body, maxsplit=1, flags=re.I)[0]
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def metadata(path, kind, locale, stamp):
    old = path.read_text(encoding="utf-8")
    if 'name="robots" content="noindex"' in old:
        return old
    title = html.unescape(re.search(r"<title>(.*?)</title>", old, re.S | re.I).group(1)).strip()
    title = SHORT_TITLES.get((kind, locale), title)
    if len(title) >= 60:
        title = "CyrFlip - " + title.replace("CyrFlip", "").strip(" -—")[:45].rstrip()
    description = html.unescape(re.search(r'<meta name="description" content="([^"]*)"', old, re.I).group(1))
    canonical = url(kind, locale)
    og_description_match = re.search(r'<meta property="og:description" content="([^"]*)"', old, re.I)
    og_description = html.unescape(og_description_match.group(1)) if og_description_match else description
    if len(description) >= 150 or description.endswith("VS Code."):
        description = og_description if len(og_description) < 160 else description[:145].rsplit(" ", 1)[0].rstrip(" ,;:") + "."
    image = "https://raw.githubusercontent.com/SerZhyAle/CyrFlip/main/assets/social-preview.png"
    json_ld = {"@context": "https://schema.org", "@type": "TechArticle" if kind == "guide" else "WebPage",
               "headline": title, "url": canonical, "description": description, "inLanguage": locale,
               "about": {"@type": "SoftwareApplication", "name": "CyrFlip", "operatingSystem": "Windows"}}
    block = ["  <!-- doc-quality metadata: generated by tools/site/sync-doc-quality.py -->",
             "  <title>" + html.escape(title) + "</title>",
             '  <meta name="description" content="' + html.escape(description, quote=True) + '">',
             '  <link rel="canonical" href="' + canonical + '">',
             '  <meta property="og:title" content="' + html.escape(title, quote=True) + '">',
             '  <meta property="og:description" content="' + html.escape(og_description, quote=True) + '">',
             '  <meta property="og:image" content="' + image + '">',
             '  <meta property="og:url" content="' + canonical + '">',
             '  <meta property="og:type" content="' + ("article" if kind == "guide" else "website") + '">',
             '  <meta name="twitter:card" content="summary_large_image">',
             '  <meta name="twitter:title" content="' + html.escape(title, quote=True) + '">',
             '  <meta name="twitter:description" content="' + html.escape(og_description, quote=True) + '">',
             '  <meta name="twitter:image" content="' + image + '">']
    block += ['  <link rel="alternate" hreflang="' + code + '" href="' + url(kind, code) + '">'
              for code in TRANSLATED[kind]]
    block += ['  <script type="application/ld+json">' + json.dumps(json_ld, ensure_ascii=False, separators=(",", ":")) + '</script>']
    if locale != "en":
        existing = re.search(r'<meta name="source-sha256" content="([a-f0-9]{64})"\s*/?>', old)
        digest = source_hash(kind) if stamp or existing is None else existing.group(1)
        block.append('  <meta name="source-sha256" content="' + digest + '">')
    block.append("  <!-- /doc-quality metadata -->")
    if '<!-- doc-quality metadata:' in old:
        return re.sub(r'  <!-- doc-quality metadata:.*?<!-- /doc-quality metadata -->',
                      "\n".join(block), old, count=1, flags=re.S)
    # Remove the legacy head fields, preserving unrelated styling, scripts and icons.
    old = re.sub(r'\s*<title>.*?</title>', '', old, count=1, flags=re.S | re.I)
    old = re.sub(r'\s*<meta (?:name="(?:description|twitter:[^"]+|source-sha256)"|property="og:[^"]+")[^>]*>', '', old, flags=re.I)
    old = re.sub(r'\s*<link rel="(?:canonical|alternate)"[^>]*>', '', old, flags=re.I)
    old = re.sub(r'\s*<script type="application/ld\+json">.*?</script>', '', old, flags=re.S | re.I)
    return old.replace("<head>", "<head>\n" + "\n".join(block), 1)


def generated_files():
    pages = [(kind, locale, page(kind, locale)) for kind, locales in TRANSLATED.items()
             for locale in locales if page(kind, locale).exists()]
    urls = [url(kind, locale) for kind, locale, _ in pages]
    sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    sitemap += "".join("  <url><loc>" + address + "</loc></url>\n" for address in sorted(urls))
    sitemap += "</urlset>\n"
    index = []
    for kind, locale, path in pages:
        text = path.read_text(encoding="utf-8")
        title = html.unescape(re.search(r"<title>(.*?)</title>", text, re.S | re.I).group(1))
        description = html.unescape(re.search(r'<meta name="description" content="([^"]*)"', text).group(1))
        headings = [html.unescape(re.sub(r"<[^>]+>", "", heading)).strip() for heading in
                    re.findall(r"<h[1-3]\b[^>]*>(.*?)</h[1-3]>", text, re.S | re.I)]
        index.append({"url": url(kind, locale), "lang": locale, "title": title,
                      "description": description, "headings": headings})
    return {DOCS / "sitemap.xml": sitemap,
            DOCS / "search-index.json": json.dumps(index, ensure_ascii=False, indent=2) + "\n"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stamp-translations", action="store_true")
    args = parser.parse_args()
    if args.stamp_translations and not args.write:
        parser.error("--stamp-translations requires --write")
    failures = []
    for kind, locales in TRANSLATED.items():
        for locale in locales:
            path = page(kind, locale)
            if not path.exists():
                failures.append("missing " + str(path))
                continue
            actual = path.read_text(encoding="utf-8")
            expected = metadata(path, kind, locale, args.stamp_translations)
            if actual != expected:
                if args.write:
                    path.write_text(expected, encoding="utf-8", newline="\n")
                else:
                    failures.append("metadata drift: " + str(path.relative_to(ROOT)))
            if locale != "en" and source_hash(kind) not in expected:
                failures.append("stale translation: " + str(path.relative_to(ROOT)))
    for path, expected in generated_files().items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            if args.write:
                path.write_text(expected, encoding="utf-8", newline="\n")
            else:
                failures.append("generated file drift: " + str(path.relative_to(ROOT)))
    if failures:
        print("\n".join(failures))
        return 1
    print("documentation quality: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
