using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;

namespace IconGen
{
    /// <summary>
    /// The <c>glyphs</c> verb (ticket S0022 A1): copies the vocabulary glyphs CyrFlip draws out of the
    /// shared catalog into <c>src/CyrFlip/Glyphs.g.cs</c> as SVG path data, which the app fills with GDI+
    /// at draw time (<c>GlyphRenderer</c>). The catalog root is an argument, never a literal path.
    ///
    /// Compatibility law (VERSIONING section 4) as it applies to this one reader:
    /// glyphs are found by file name and records by key, never by position; fields this tool does not
    /// know are ignored; a MAJOR other than 0 stops the run naming ICON-SET; an unknown enum value takes
    /// its documented default and says so; an id the catalog no longer has fails the run and leaves the
    /// previous file untouched (absence is not authority to drop a glyph the app draws).
    /// </summary>
    internal static class GlyphVendoring
    {
        private const string Contract = "ICON-SET";

        public static int Run(string root, string[] args)
        {
            string? catalog = ArgValue(args, "-CatalogRoot");
            if (string.IsNullOrWhiteSpace(catalog)) return Fail("Usage: glyphs -CatalogRoot <catalog folder> [-Ids <file>] [-Out <file>]");
            string iconography = Path.Combine(catalog, "iconography");
            string idsFile = ArgValue(args, "-Ids") ?? Path.Combine(root, "tools", "IconGen", "glyph-ids.txt");
            string outFile = ArgValue(args, "-Out") ?? Path.Combine(root, "src", "CyrFlip", "Glyphs.g.cs");

            if (!Directory.Exists(iconography)) return Fail("ICON-SET: folder not found: " + iconography);
            if (!File.Exists(idsFile)) return Fail("Id list not found: " + idsFile);

            string? version = ReadContractVersion(Path.Combine(iconography, "README.md"));
            if (version == null) return Fail(Contract + ": no contract block with a version in iconography/README.md");
            if (!version.StartsWith("0.", StringComparison.Ordinal))
                return Fail(Contract + " version " + version + ": this reader knows MAJOR 0 only, nothing written");

            string[] ids = File.ReadAllLines(idsFile)
                .Select(l => { int hash = l.IndexOf('#'); return (hash >= 0 ? l.Substring(0, hash) : l).Trim(); })
                .Where(l => l.Length > 0).Distinct(StringComparer.Ordinal).OrderBy(l => l, StringComparer.Ordinal).ToArray();
            if (ids.Length == 0) return Fail("Id list is empty: " + idsFile);

            Dictionary<string, Dictionary<string, object>> vocabulary = ReadVocabulary(Path.Combine(iconography, "vocabulary.jsonl"));
            var builder = new StringBuilder();
            builder.Append("// <auto-generated>\n");
            builder.Append("// Generated by tools/IconGen (glyphs verb) from the ").Append(Contract).Append(" catalog, version ").Append(version).Append(".\n");
            builder.Append("// Never edit by hand: change tools/IconGen/glyph-ids.txt and run\n");
            builder.Append("//   dotnet run --project tools/IconGen -- glyphs -CatalogRoot <catalog>\n");
            builder.Append("// </auto-generated>\n");
            builder.Append("namespace CyrFlip\n{\n");
            builder.Append("    internal static class Glyphs\n    {\n");
            builder.Append("        internal const string CatalogVersion = \"").Append(version).Append("\";\n\n");
            builder.Append("        internal static readonly GlyphRecord[] All =\n        {\n");

            foreach (string id in ids)
            {
                string svgPath = Path.Combine(iconography, "glyphs", id + ".svg");
                if (!File.Exists(svgPath)) return Fail(Contract + ": glyph file missing for '" + id + "' (" + svgPath + "); nothing written");
                string baseId = id.Contains("--") ? id.Substring(0, id.IndexOf("--", StringComparison.Ordinal)) : id;
                if (!vocabulary.TryGetValue(baseId, out Dictionary<string, object>? record))
                    return Fail(Contract + ": no vocabulary record for '" + baseId + "'; nothing written");

                if (!TryReadSvg(File.ReadAllText(svgPath), out string d, out float[]? matrix, out string problem))
                    return Fail(Contract + ": " + id + ".svg: " + problem);

                string status = EnumValue(record, "status", new[] { "active", "proposed" }, "proposed", id);
                string rtl = EnumValue(record, "rtl", new[] { "fixed", "mirror" }, "fixed", id);
                EnumValue(record, "colour", new[] { "content", "accent", "category", "state", "brand", "fixed" }, "content", id);
                string source = "";
                if (record.TryGetValue("ref", out object? refValue) && refValue is Dictionary<string, object> refMap
                    && refMap.TryGetValue("source", out object? src) && src is string text) source = text;

                builder.Append("            new GlyphRecord(\"").Append(id).Append("\", \"").Append(Escape(d)).Append("\", ");
                if (matrix == null) builder.Append("null");
                else builder.Append("new float[] { ").Append(string.Join(", ", matrix.Select(v => v.ToString("R", CultureInfo.InvariantCulture) + "f"))).Append(" }");
                builder.Append(", \"").Append(status).Append("\", \"").Append(rtl).Append("\", \"").Append(Escape(source)).Append("\"),\n");
            }
            builder.Append("        };\n    }\n}\n");

            Directory.CreateDirectory(Path.GetDirectoryName(outFile)!);
            File.WriteAllText(outFile, builder.ToString(), new UTF8Encoding(false));
            Console.WriteLine("Vendored " + ids.Length + " glyphs from " + Contract + " " + version + " into " + outFile);
            return 0;
        }

        private static int Fail(string message) { Console.Error.WriteLine(message); return 1; }

        private static string? ArgValue(string[] args, string name)
        {
            for (int i = 0; i < args.Length - 1; i++)
                if (string.Equals(args[i], name, StringComparison.OrdinalIgnoreCase)) return args[i + 1];
            return null;
        }

        /// <summary>The version of the ICON-SET block: read by key from the README's contract block, not by line number.</summary>
        internal static string? ReadContractVersion(string readme)
        {
            if (!File.Exists(readme)) return null;
            Match block = Regex.Match(File.ReadAllText(readme), @"```contract\s*\r?\n\s*id:\s*" + Contract + @"\s*\r?\n\s*version:\s*([0-9]+\.[0-9]+)", RegexOptions.CultureInvariant);
            return block.Success ? block.Groups[1].Value : null;
        }

        private static Dictionary<string, Dictionary<string, object>> ReadVocabulary(string file)
        {
            var serializer = new JavaScriptSerializer();
            var map = new Dictionary<string, Dictionary<string, object>>(StringComparer.Ordinal);
            foreach (string line in File.ReadAllLines(file))
            {
                if (string.IsNullOrWhiteSpace(line)) continue;
                try
                {
                    var record = serializer.Deserialize<Dictionary<string, object>>(line);
                    if (record != null && record.TryGetValue("id", out object? id) && id is string key) map[key] = record;
                }
                catch (Exception) { /* a line this reader cannot parse is not a record it asked for */ }
            }
            return map;
        }

        private static string EnumValue(Dictionary<string, object> record, string key, string[] known, string fallback, string id)
        {
            if (record.TryGetValue(key, out object? value) && value is string text && known.Contains(text)) return text;
            Console.WriteLine("  note: " + id + " has " + (value == null ? "no" : "unknown") + " '" + key + "' - using the default '" + fallback + "'");
            return fallback;
        }

        private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");

        /// <summary>
        /// One <c>&lt;path d&gt;</c>, optionally inside a <c>&lt;g transform&gt;</c> made of translate and scale
        /// (the two files the exporter normalised into the ink box). Anything else is refused by name, so a
        /// glyph the renderer could draw wrongly is a generator failure rather than a silent misdrawing.
        /// </summary>
        internal static bool TryReadSvg(string svg, out string pathData, out float[]? matrix, out string problem)
        {
            pathData = ""; matrix = null; problem = "";
            foreach (Match tag in Regex.Matches(svg, @"<\s*([A-Za-z][A-Za-z0-9]*)"))
            {
                string name = tag.Groups[1].Value;
                if (name != "svg" && name != "path" && name != "g") { problem = "element <" + name + "> is not supported"; return false; }
            }
            MatchCollection paths = Regex.Matches(svg, @"<path\b[^>]*?\bd\s*=\s*""([^""]*)""", RegexOptions.Singleline);
            if (paths.Count != 1) { problem = "expected exactly one <path>, found " + paths.Count; return false; }
            if (Regex.IsMatch(svg, @"fill-rule|opacity|<path[^>]*transform")) { problem = "fill-rule, opacity or a path transform is not supported"; return false; }
            pathData = Regex.Replace(paths[0].Groups[1].Value.Trim(), @"\s+", " ");

            Match group = Regex.Match(svg, @"<g\b[^>]*\btransform\s*=\s*""([^""]*)""");
            if (!group.Success) return true;
            float[] m = { 1, 0, 0, 1, 0, 0 };
            foreach (Match op in Regex.Matches(group.Groups[1].Value, @"(translate|scale)\s*\(([^)]*)\)"))
            {
                float[] v = Regex.Split(op.Groups[2].Value.Trim(), @"[\s,]+")
                    .Select(t => float.Parse(t, CultureInfo.InvariantCulture)).ToArray();
                float[] o = op.Groups[1].Value == "translate"
                    ? new[] { 1f, 0f, 0f, 1f, v[0], v.Length > 1 ? v[1] : 0f }
                    : new[] { v[0], 0f, 0f, v.Length > 1 ? v[1] : v[0], 0f, 0f };
                m = Multiply(m, o);
            }
            if (Regex.Replace(group.Groups[1].Value, @"(translate|scale)\s*\([^)]*\)|\s", "").Length != 0)
            { problem = "group transform other than translate and scale"; return false; }
            matrix = m;
            return true;
        }

        // SVG matrices [a b c d e f]; the result applies `right` first, then `left`.
        private static float[] Multiply(float[] l, float[] r) => new[]
        {
            l[0] * r[0] + l[2] * r[1], l[1] * r[0] + l[3] * r[1],
            l[0] * r[2] + l[2] * r[3], l[1] * r[2] + l[3] * r[3],
            l[0] * r[4] + l[2] * r[5] + l[4], l[1] * r[4] + l[3] * r[5] + l[5],
        };
    }
}
