using System;
using System.IO;
using System.Linq;
using System.Text;
using CyrFlip;
using Xunit;

namespace CyrFlip.Tests
{
    /// <summary>
    /// SCENARIO-FILE 0.10, section 7 item G: "a current-shape vector from each real writer is owed, each
    /// generated by that writer". This is CyrFlip's. The file in <c>Fixtures/ScenarioFile/</c> is what
    /// <see cref="LauncherScenarioStore.Export"/> writes for one fixed scenario - byte for byte - and is
    /// <b>generated, never typed</b>: run <see cref="TheVectorIsWhatTheWriterWrites"/> with
    /// <c>CYRFLIP_WRITE_SCENARIO_VECTORS=1</c> to rewrite it, then copy it to the catalog's
    /// <c>launch-scenarios/vectors/</c>. Without the variable the test fails whenever the file and the
    /// writer disagree, so neither can drift. The shape facts of item G are asserted on their own too,
    /// because a vector that merely matches today's writer would also match a writer that had quietly
    /// started to emit a BOM or the carrier.
    /// </summary>
    public class ScenarioFileWriterVectorTests : IDisposable
    {
        private static readonly string VectorPath = Path.GetFullPath(Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "Fixtures", "ScenarioFile", "cyrflip_current_shape.xml"));

        private readonly string _folder = Path.Combine(
            Path.GetTempPath(), "CyrFlipTests", Guid.NewGuid().ToString("N"));

        public void Dispose()
        {
            try { Directory.Delete(_folder, recursive: true); } catch { }
        }

        private static LauncherScenario Sample() => new LauncherScenario
        {
            Id = Guid.Parse("0f3b6c1e-8a42-4d97-b5e0-6c1d9a7f2e84"),
            Name = "Calculator",
            Path = "calc.exe",
            Filename = "0f3b6c1e-8a42-4d97-b5e0-6c1d9a7f2e84.xml",
        };

        private byte[] Write()
        {
            Directory.CreateDirectory(_folder);
            string file = Path.Combine(_folder, "exported.xml");
            new LauncherScenarioStore(Path.Combine(_folder, "store")).Export(Sample(), file);
            return File.ReadAllBytes(file);
        }

        [Fact]
        public void TheVectorIsWhatTheWriterWrites()
        {
            byte[] written = Write();
            if (Environment.GetEnvironmentVariable("CYRFLIP_WRITE_SCENARIO_VECTORS") == "1")
            {
                Directory.CreateDirectory(Path.GetDirectoryName(VectorPath)!);
                File.WriteAllBytes(VectorPath, written);
            }
            Assert.True(File.Exists(VectorPath), "missing " + VectorPath);
            Assert.Equal(written, File.ReadAllBytes(VectorPath));
        }

        [Fact]
        public void TheWriterShapeIsTheOneItemGDescribes()
        {
            byte[] bytes = Write();
            string text = new UTF8Encoding(false).GetString(bytes);

            Assert.False(bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF, "UTF-8 without a byte-order mark");
            Assert.StartsWith("<?xml version=\"1.0\"?>", text);                       // no encoding declaration
            Assert.True(text.IndexOf("xmlns:xsd", StringComparison.Ordinal) < text.IndexOf("xmlns:xsi", StringComparison.Ordinal),
                "xmlns:xsd is declared before xmlns:xsi");
            Assert.Contains("\r\n", text);
            Assert.DoesNotContain("schemaVersion", text);                              // writers keep omitting the carrier
            Assert.Contains("<Hotkey />", text);                                       // the extension, always present
            Assert.Contains("<Arguments />", text);                                    // an empty string is a self-closed element
        }

        [Fact]
        public void EveryModelElementIsWrittenIncludingItsDefault()
        {
            string text = new UTF8Encoding(false).GetString(Write());

            foreach (string element in new[]
                { "Id", "Name", "Path", "Arguments", "WorkingDirectory", "Filename", "RunAsAdmin", "Order", "Type",
                  "YtDlpOutputFolder", "YtDlpFormat", "Hotkey" })
                Assert.True(text.Contains("<" + element + ">") || text.Contains("<" + element + " />"), element);
        }

        [Fact]
        public void TheWritersOwnFileReadsBackAsTheSameScenario()
        {
            Write();
            LauncherScenario? read = LauncherScenarioStore.TryRead(Path.Combine(_folder, "exported.xml"), out Exception? error);

            Assert.Null(error);
            LauncherScenario expected = Sample();
            Assert.Equal(expected.Id, read!.Id);
            Assert.Equal(expected.Name, read.Name);
            Assert.Equal(expected.Path, read.Path);
            Assert.Equal(LauncherScenarioType.Executable, read.Type);
        }

        [Fact]
        public void TheVectorFileReadsThroughTheReader()
        {
            Assert.True(File.Exists(VectorPath), "missing " + VectorPath);
            LauncherScenario? read = LauncherScenarioStore.TryRead(VectorPath, out Exception? error);

            Assert.Null(error);
            Assert.Equal(Sample().Id, read!.Id);
        }
    }
}
